equinor/flotilla

src/components/InfoButton/InfoButton.tsx, src/components/RobotOverview/RobotInfoButton.tsx, src/components/RobotOverview/RobotOverview.tsx, src/components/RobotOverview/robotOverview.module.css
=> Add extra robot info button

src/components/RobotOverview/RobotOverview.tsx, src/components/RobotOverview/RobotOverviewHeader.tsx, src/components/RobotOverview/RobotStatusView.tsx, src/components/RobotOverview/robotOverview.module.css
=> Add RobotStatusView component

backend/.gitignore, backend/README.md, backend/setup.py, backend/src/flotilla/api/robots_api.py, backend/src/flotilla/database/crud/crud.py, backend/src/flotilla/database/mock_database/mock_database.py, backend/src/flotilla/database/models.py, backend/src/flotilla/main.py, backend/tests/conftest.py, backend/tests/test_api.py, backend/tests/test_crud.py
=> Add basic robots endpoints

.github/workflows/pythonpackage.yml, backend/setup.py
=> Add testing and linting workflow

docker-compose.yml, frontend/.gitignore, frontend/Dockerfile, frontend/package.json
=> Change default port for frontend to 3001

backend/src/flotilla/api/robots_api.py, backend/src/flotilla/database/crud/crud.py, backend/src/flotilla/database/mock_database/mock_database.py, backend/src/flotilla/database/models.py, backend/tests/test_crud.py, backend/tests/test_db.py
=> Add DBModel suffix to db models

backend/.gitignore, backend/README.md, backend/src/flotilla/api/missions_api.py, backend/src/flotilla/api/robots_api.py, backend/src/flotilla/config/log_config.py, backend/src/flotilla/main.py, backend/tests/test_api/test_robots_api.py
=> Add backend logging

frontend/src/models/robot.ts
Small PR just to get going with Flotilla development
=> Fix line formatting

backend/src/flotilla/config/log_config.py, backend/src/flotilla/main.py
=> Add logging with api-logger to all endpoints

backend/src/flotilla/api/events_api.py, backend/src/flotilla/database/db.py, backend/src/flotilla/database/mock_database/mock_database.py, backend/src/flotilla/main.py, backend/tests/conftest.py, backend/tests/test_api/test_events_api.py, backend/tests/test_api/test_robots_api.py, backend/tests/test_crud.py
Closes #83 
~~This PR includes the commits from #101 , the plan is to rebase once that one is merged
Only the last 3 commits belong to this PR~~
=> Feature - Access database in tests

backend/README.md
Add the --upgrade flag to the `flotilla-openapi` installation to
ensure the newest version is installed.
=> Refactor README.md

backend/src/flotilla/api/events_api.py, backend/src/flotilla/api/main.py, backend/src/flotilla/api/pagination.py, backend/src/flotilla/api/reports_api.py, backend/src/flotilla/api/robots_api.py, backend/src/flotilla/database/crud.py, backend/src/flotilla/database/db.py, backend/src/flotilla/services/events/event_handler.py, backend/src/flotilla/settings/settings.py, backend/tests/test_api/test_events_api.py, backend/tests/test_api/test_robots_api.py, backend/tests/test_crud.py
=> Add pagination for certain GET requests

backend/src/flotilla/api/events_api.py, backend/src/flotilla/api/missions_api.py, backend/src/flotilla/api/reports_api.py, backend/src/flotilla/api/robots_api.py, backend/src/flotilla/database/crud.py, backend/src/flotilla/database/models.py, backend/src/flotilla/settings/settings.py, backend/tests/test_api/test_robots_api.py
=> Add endpoint to create and enable robots

backend/src/flotilla/api/events_api.py, backend/src/flotilla/api/filter.py, backend/src/flotilla/api/reports_api.py, backend/src/flotilla/api/robots_api.py, backend/src/flotilla/database/crud.py, backend/src/flotilla/database/mock_database/mock_database.py, backend/src/flotilla/database/models.py, backend/src/flotilla/services/events/event_handler.py, backend/tests/test_api/test_events_api.py, backend/tests/test_api/test_reports_api.py, backend/tests/test_api/test_robots_api.py, backend/tests/test_crud.py
=> Add filtering options for GET endpoints

.gitignore, backend/api/Configurations/ConfigureSwagger.cs, backend/api/Program.cs, backend/api/api.csproj, backend/api/appsettings.Development.json, backend/api/appsettings.json, backend/backend.sln
Closes #158 
With this Authorization scheme, the user will need to have the role "Role.User", which is managed here:
https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Users/objectId/8256d35d-5c07-440b-9f47-4abce94c8565/appId/ea4c7b92-47b3-45fb-bd25-a8070f0c495c
=> Dotnet add authorization

.github/workflows/backend_lint_and_test.yml, backend/README.md, backend/api.test/TestRobotController.cs, backend/api.test/api.test.csproj, backend/api/Context/FlotillaDbContext.cs, backend/api/Controllers/RobotController.cs, backend/backend.sln
=> Set up unit testing in dotnet

.editorconfig, .github/workflows/backend_lint_and_test.yml, backend/README.md, backend/api.test/TestRobotController.cs, backend/api.test/api.test.csproj, backend/api/Configurations/ConfigureSwagger.cs, backend/api/Context/FlotillaDbContext.cs, backend/api/Context/InitDb.cs, backend/api/Controllers/RobotController.cs, backend/api/Models/Models.cs, backend/api/Program.cs, backend/api/Services/RobotService.cs, backend/api/api.csproj
Closes #168 
~~Included #181 to avoid too many conflicts, will rebase once #181 is merged~~
=> Set up formatting in dotnet

backend/Dockerfile, backend/api/Properties/launchSettings.json, backend/api/api.csproj, docker-compose.yml
=> Add Dockerfile, update ports

backend/README.md
=> Update readme for dotnet

backend/api/Program.cs, backend/api/api.csproj, backend/api/appsettings.Development.json, frontend/src/authConfig.tsx
Also updated the AzureAD resources to allow for this authentication flow.
Backend registration: https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/ea4c7b92-47b3-45fb-bd25-a8070f0c495c/isMSAApp/
Frontend registration: https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/f5993820-b7e2-4791-886f-f9f5027dc7be/isMSAApp/
=> Add CORS to dotnet backend API

backend/api/Controllers/Models/CreateRobotQuery.cs, backend/api/Controllers/ReportController.cs, backend/api/Controllers/RobotController.cs, backend/api/Services/RobotService.cs
=> Fix no id required to create

.github/workflows/frontend_lint_and_test.yml, frontend/README.md, frontend/package.json, frontend/src/App.tsx, frontend/src/authConfig.tsx, frontend/src/components/RobotOverview/BatteryStatusView.tsx, frontend/src/components/RobotOverview/RobotOverview.tsx, frontend/src/components/SignInPage/ApiCaller.tsx, frontend/src/components/SignInPage/ProfileContent.tsx, frontend/src/components/SignInPage/SignInButton.tsx, frontend/src/components/SignInPage/SignInPage.tsx, frontend/src/index.tsx, frontend/src/models/robot.ts, frontend/src/models/schema.ts
=> Fix prettier action

backend/api/MQTT/MqttService.cs, backend/api/appsettings.Development.json, broker/Dockerfile, broker/README.md, broker/mosquitto/config/access_control, broker/mosquitto/config/mosquitto.conf, broker/mosquitto/config/passwd_file
=> Authentication for mqtt

backend/api/Controllers/RobotController.cs, backend/api/Database/Models/Report.cs, backend/api/Services/IsarService.cs
=> Add endpoints to pause and resume a mission

broker/README.md
Forgot some instructions related to #260
=> Update broker readme with TLS instructions

setup.sh
Forgot to add warning for frontend env
=> Feature create setup script

backend/api/MQTT/MqttService.cs, backend/api/api.csproj
Removing workaround after new MQTT release fixing bug
https://github.com/dotnet/MQTTnet/releases/tag/v4.0.2.221
=> Update MQTT.NET and remove workaround

backend/api.test/EventHandlers/TestScheduledMissionEventHandler.cs, backend/api.test/Services/ReportService.cs, backend/api/Controllers/RobotController.cs, backend/api/Database/Context/InitDb.cs, backend/api/Database/Models/Report.cs, backend/api/Services/IsarService.cs, backend/api/Services/ReportService.cs
After a couple of rebases, the change of the echo mission ID was not complete.
This PR fixes the bugs related to this.
=> Fix all references to echo mission ID to int

backend/api.test/api.test.csproj, backend/api/Database/Context/InitDb.cs, backend/api/MQTT/MqttService.cs, backend/api/Program.cs, frontend/src/App.tsx, frontend/src/components/Contexts/AssetContext.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/MissionPage.tsx, frontend/src/components/TaskOverview/TaskTable.tsx
=> Add asset select functionality

frontend/Dockerfile.Radix
After adding Tenant ID as an env variable, forgot to add it to dockerfile
=> Add tenant ID to Radix dockerfile

frontend/public/index.html, frontend/src/components/MissionOverview/MissionCard.tsx, frontend/src/components/MissionOverview/OngoingMissionCard.tsx, frontend/src/components/RobotCards/RobotStatusCard.tsx, frontend/src/components/VideoStream/VideoStreamWindow.tsx
Use Equinor front 
Reduce shadow around cards
=> Polish frontend 

backend/api/EventHandlers/MqttEventHandler.cs, backend/api/MQTT/MqttService.cs, backend/api/appsettings.json
=> Elevate log levels to reduce backend log output

frontend/package-lock.json, frontend/package.json
=> Remove openapi dependency from frontend

backend/api.test/Controllers/TestRobotController.cs, backend/api/Controllers/Models/IsarMissionDefinition.cs, backend/api/Program.cs, backend/api/Services/IsarService.cs, backend/api/appsettings.json
=> Use downstream api for calls and authentication to ISAR

.github/workflows/publish_docker_image.yml
=> Add workflow to publish docker images

.gitattributes, frontend/src/components/MissionOverview/UpcomingMissionView.tsx
The frontend was calling GET EchoMissions constantly every millisecond.
This PR changes it so that this call is also polled every second along with the other polling API calls.
=> Bug - Constant backend call to GET EchoMissions

backend/api/Configurations/ConfigurationBuilderExtensions.cs, backend/api/Program.cs
=> Add custom logging configuration with timestamp

backend/api/Controllers/EchoMissionController.cs, backend/api/Controllers/EchoPlantController.cs, backend/api/Controllers/MissionController.cs, backend/api/Controllers/RobotController.cs, frontend/src/api/ApiCaller.tsx
Just some updates on swagger documentation as well as a rename of echo-plants endpoint from 
"/all-plants-infos" to "/echo-plants"
=> Update swagger documentation

backend/README.md, backend/api/Program.cs, backend/api/api.csproj
=> Setup application insights

frontend/src/components/MapPosition/MapPositionView.tsx, frontend/src/components/Pages/MissionPage.tsx
=> Display robot pose in Frontend

frontend/README.md, frontend/src/components/Pages/MissionPage.tsx, frontend/src/components/VideoStream/VideoSection.tsx, frontend/src/components/VideoStream/VideoStreamWindow.tsx
=> Add placeholder for missing videostream

frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
=> Align Pause and Stop button on Mission Page

frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/UpcomingMissionView.tsx
Instead of waiting for echoMissions and robotOptions to load before rendering the buttons, the "schedule mission" button render in a disabled state while waiting for the parameters to load
=> Fix delayed render of "schedule mission"-button

frontend/src/components/Contexts/AssetContext.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/UpcomingMissionView.tsx
The variable assetString didn't update correctly. Solved by getting asset value directly
=> Require asset

frontend/src/index.tsx
Added a callback function to handle (log) errors during login. 
For example if the wrong scope is requested, we will now see this in the console.
=> Add error handling callback for login

.github/release.yml
copied from the ISAR repository
=> Add release specification

backend/api/Database/Models/MissionMap.cs, backend/api/Services/Models/TransformationMatrices.cs
=> Fix mission not including map properties

.gitignore, backend/api.test/Controllers/TestMissionController.cs, backend/api.test/Controllers/TestRobotController.cs, backend/api.test/EventHandlers/TestMissionScheduler.cs, backend/api.test/Services/MissionService.cs, backend/api/Controllers/MissionController.cs, backend/api/Database/Models/Mission.cs, backend/api/MQTT/MqttService.cs, backend/api/Services/MissionService.cs, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionProgressDisplay.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionStatusDisplay.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/UpcomingMissionCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/UpcomingMissionView.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx, frontend/src/models/Mission.ts
Closes #509 
Closes #540 
Related to #545 
Gives an error to user for missions failing within last 10 minutes.
When one mission has failed, you can click it to get to the details.
If more than one mission failed in the last 10 minutes, you should look at the recent missions for information (#545 )
Recommend going through it commit by commit! :)
=> Add warning message for failing missions

backend/api/appsettings.Development.json, backend/api/appsettings.Production.json, backend/api/appsettings.Staging.json
for the different environments (Development, Staging, Production)
=> Update ClientId and keyvault information

backend/api/Controllers/MissionController.cs, backend/api/appsettings.Development.json
=> Add default map to scheduled missions

backend/api/appsettings.Development.json
=> Map name bug

frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/PastMissionCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/PastMissionsView.tsx
Closes #545 
Changed name to 'Past Missions' because there is no guarantee they are recent.
=> Feature add recent mission section

frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/UpcomingMissionView.tsx
=> Feature dismiss error message

backend/api.test/Controllers/TestMissionController.cs, backend/api.test/Mocks/IsarServiceMock.cs, backend/api/Controllers/MissionController.cs, backend/api/Controllers/Models/IsarMissionDefinition.cs, backend/api/Controllers/RobotController.cs, backend/api/Database/Context/InitDb.cs, backend/api/Database/Models/PlannedTask.cs, backend/api/Database/Models/Robot.cs, backend/api/Services/IsarService.cs, backend/api/Services/StidService.cs, backend/api/Utilities/TagPositioner.cs
Should fix the current bugs related to the backend's communication with ISAR.
Also has some other small fixes
Should be readable if reviewing commit by commit
=> Fix backend

backend/api/Program.cs
Add a write line so that when developing we are always certain what environment is being run
=> Add write line for environment

.github/workflows/notifyMigrationChanges.yml, .github/workflows/notifyPossibleMigrationUpdate.yml, .github/workflows/promoteToProduction.yml, .github/workflows/promoteToStaging.yml, .github/workflows/runMigrations.yml, .github/workflows/updateDatabase.yml, backend/README.md
=> Database migration pipelines

.github/workflows/notifyMigrationChanges.yml, .github/workflows/notifyPossibleMigrationUpdate.yml, .github/workflows/updateDatabase.yml
=> Update version on comment action

.github/workflows/updateDatabase.yml
=> Check if reviews are empty

backend/api/appsettings.Development.json, backend/api/appsettings.Production.json, backend/api/appsettings.Staging.json, backend/api/appsettings.Test.json, backend/api/appsettings.json
=> Set default log level to warning

backend/api/Database/Models/Robot.cs, backend/api/MQTT/MqttService.cs, backend/api/appsettings.json
=> Fix http for isar

frontend/src/components/Pages/FrontPage/MissionOverview/PastMissionsView.tsx, frontend/src/models/Mission.ts
=> Show partially successful in past missions

backend/api/appsettings.Development.json, backend/api/appsettings.Production.json, backend/api/appsettings.Staging.json, backend/api/appsettings.json
=> Fix ISAR auth wrong client ids

backend/api/Database/Models/VideoStream.cs, backend/api/EventHandlers/MqttEventHandler.cs
The video streams were not being properly updated.
Refactored and also included what was updated in the logs.
=> Fix bug in updating video stream

backend/api/Database/Context/InitDb.cs
The ISAR Id is required so we need to add it in the local test database
=> Add IsarId to local database

backend/api.test/Mocks/MapServiceMock.cs, backend/api/Controllers/MissionController.cs, backend/api/Services/MapService.cs
=> Remove System.Drawing dependency

backend/api/EventHandlers/MissionScheduler.cs
=> Order mission queue by time in backend

backend/api.test/EventHandlers/TestMissionScheduler.cs, backend/api.test/Mocks/RobotControllerMock.cs, backend/api.test/Services/MissionService.cs, backend/api/Controllers/RobotController.cs, backend/api/Database/Context/InitDb.cs, backend/api/Database/Models/Inspection.cs, backend/api/Database/Models/Mission.cs, backend/api/Database/Models/MissionTask.cs, backend/api/Database/Models/Robot.cs, backend/api/Database/Models/VideoStream.cs, backend/api/EventHandlers/IsarConnectionEventHandler.cs, backend/api/EventHandlers/MissionScheduler.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Migrations/20230412063135_AddCurrentMissionIdToRobot.Designer.cs, backend/api/Migrations/20230412063135_AddCurrentMissionIdToRobot.cs, backend/api/Services/MapService.cs, backend/api/Services/MissionService.cs, backend/api/Services/Models/IsarMissionDefinition.cs, backend/api/Services/RobotService.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx, frontend/src/components/Pages/MissionHistoryPage/HistoricMissionCard.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx, frontend/src/language/en.json, frontend/src/language/no.json
Closes #716 
Closes #733 
Most commits are only a couple of lines
=> Stop mission if ISAR unreachable

frontend/src/api/ApiCaller.tsx, frontend/src/models/MissionQueryParameters.ts
=> Filter missions by currently selected asset

backend/api/Controllers/MissionController.cs, backend/api/Controllers/Models/CustomMissionQuery.cs, backend/api/Database/Models/Inspection.cs, backend/api/Database/Models/MissionTask.cs
=> Add support for scheduling custom json missions

backend/api/Services/Models/IsarMissionDefinition.cs
=> Set tag to optional in IsarMission

backend/api.test/EventHandlers/TestMissionScheduler.cs, backend/api.test/Mocks/RobotControllerMock.cs, backend/api.test/Services/RobotService.cs, backend/api/Controllers/Models/CreateRobotModelQuery.cs, backend/api/Controllers/Models/CreateRobotQuery.cs, backend/api/Controllers/Models/UpdateRobotModelQuery.cs, backend/api/Controllers/RobotController.cs, backend/api/Controllers/RobotModelController.cs, backend/api/Database/Context/FlotillaDbContext.cs, backend/api/Database/Context/InitDb.cs, backend/api/Database/Models/Robot.cs, backend/api/Database/Models/RobotModel.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/MQTT/MessageModels/IsarRobotInfo.cs, backend/api/Migrations/20230426114806_AddRobotModelTable.Designer.cs, backend/api/Migrations/20230426114806_AddRobotModelTable.cs, backend/api/Program.cs, backend/api/Services/RobotModelService.cs, backend/api/Services/RobotService.cs, frontend/src/components/Contexts/AuthProvider.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotImage.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx, frontend/src/models/Robot.ts, frontend/src/models/RobotModel.ts
=> Add robot model class

backend/api/Controllers/MissionController.cs, backend/api/Services/Models/IsarMissionDefinition.cs
Depends on https://github.com/equinor/isar/pull/460
=> Send mission name to ISAR

backend/api/Services/MapService.cs
=> Select map based on most tags within map

frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
=> Open stid link in new tab

frontend/package-lock.json, frontend/package.json, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionRestartButton.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/components/Pages/SignInPage/SignInPage.tsx, frontend/src/index.tsx, frontend/src/models/CustomMission.ts, frontend/src/models/Inspection.ts, frontend/src/utils/icons.tsx
This feature enables us to easily re-run historic missions.
When clicking the icon, the popup menu appears on the side to choose full mission or partial rerun
The current implementation redirects the user to the front page.
This was done because the idea is that the front page will show the user the new mission in a context, as it may not be started right away but rather added to the queue, in which case it makes sense to see it in the queue.
The front page is also where the user will usually be after scheduling a mission.
=> Button to re-run missions

backend/api.test/Services/RobotService.cs, backend/api/Controllers/Models/CreateRobotQuery.cs, backend/api/Database/Models/Robot.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/MQTT/MessageModels/IsarRobotInfo.cs, backend/api/Migrations/20230321140202_InitialCreate.cs, backend/api/Migrations/20230412063135_AddCurrentMissionIdToRobot.cs, backend/api/Migrations/20230508063416_ChangeEstimatedDurationToInt.cs, backend/api/Migrations/20230512130313_AddCurrentAssetToRobot.Designer.cs, backend/api/Migrations/20230512130313_AddCurrentAssetToRobot.cs, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx, frontend/src/models/Robot.ts
closes #743 
Connected to https://github.com/equinor/isar/pull/463
Waiting for #776 to merge before add database migrations
=> Associate robot with plant

frontend/src/components/Pages/FrontPage/MissionOverview/CreateMissionButton.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog.tsx
=> Add popover for ipad usage

frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryPage.tsx, frontend/src/components/Pages/MissionPage/MissionPage.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx
=> Disallow changing of asset in mission view

frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Displays date in mission view

broker/README.md, frontend/src/App.tsx, frontend/src/api/ApiCaller.tsx, frontend/src/components/Contexts/AuthProvider.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlButtons.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionRestartButton.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx, frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/components/Pages/MissionPage/MissionPage.tsx, frontend/src/components/Pages/MissionPage/VideoStream/VideoPlayerOvenPlayer.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx, frontend/src/utils/MapMarkers.tsx
Removing unused code, add callbacks and other minor changes.
=> Fix all warnings in frontend

backend/api.test/Database/Models.cs, backend/api/Database/Models/Pose.cs, backend/api/Services/EchoService.cs, backend/api/Services/Models/EchoPoseResponse.cs
=> Calculate pose with quaternion clockwise rotation

frontend/src/components/Contexts/AssetContext.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx
Map blob store uses this value and fails if it receives asset containing capital letters
=> Use lower case assetCode in frontend

frontend/src/App.tsx, frontend/src/components/Contexts/MissionControlContext.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlButtons.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Link state of mission control buttons

backend/api.test/EventHandlers/TestMissionScheduler.cs, backend/api.test/Mocks/MapServiceMock.cs, backend/api.test/Services/MissionService.cs, backend/api/Controllers/AssetDeckController.cs, backend/api/Controllers/MissionController.cs, backend/api/Controllers/RobotController.cs, backend/api/Database/Context/FlotillaDbContext.cs, backend/api/Database/Context/InitDb.cs, backend/api/Database/Models/MapMetadata.cs, backend/api/Database/Models/Mission.cs, backend/api/Migrations/20230616084904_RenameMissionMap.Designer.cs, backend/api/Migrations/20230616084904_RenameMissionMap.cs, backend/api/Services/MapService.cs, backend/api/Services/Models/IsarMissionDefinition.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx, frontend/src/components/Pages/RobotPage/AssetDeckMapView.tsx, frontend/src/models/MapMetadata.ts, frontend/src/models/Mission.ts, frontend/src/utils/MapMarkers.tsx
missionMap is used both for missions and for assetDecks. Should therefor be renamed to something less mission specific
=> Rename missionMap to mapMetadata

backend/api.test/Services/RobotService.cs, backend/api/Controllers/Models/CreateRobotQuery.cs, backend/api/Controllers/Models/ScheduleLocalizationMissionQuery.cs, backend/api/Controllers/RobotController.cs, backend/api/Database/Models/Robot.cs, backend/api/Database/Models/RobotModel.cs, backend/api/EventHandlers/MqttEventHandler.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/RobotPage/LocalizationDialog.tsx
Dev is failing - I propose to revert the commits that introduce this
=> Revert commits until c9fcb1e

frontend/src/components/Contexts/MissionControlContext.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlButtons.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/StopMissionDialog.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Add confirmation dialog to stop mission button

frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx, frontend/src/components/Pages/RobotPage/AssetDeckMapView.tsx, frontend/src/utils/MapCompass.tsx, frontend/src/utils/icons.tsx
=> Add compass on maps

frontend/src/components/Contexts/LanguageContext.tsx, frontend/src/components/Pages/RobotPage/LocalizationDialog.tsx, frontend/src/language/en.json, frontend/src/language/index.tsx, frontend/src/language/no.json
=> Add feedback when localizing the robot

backend/api.test/EndpointTest.cs, backend/api.test/Mocks/BlobServiceMock.cs, backend/api.test/Mocks/CustomMissionServiceMock.cs, backend/api/Controllers/MissionController.cs, backend/api/Services/CustomMissionService.cs, backend/api/Services/MissionRunService.cs
=> Add endpoint for getting next mission run

frontend/src/components/Pages/FrontPage/MissionOverview/MissionRestartButton.tsx, frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/Mission.ts, frontend/src/utils/MapMarkers.tsx
=> Add mission rerun to translations

backend/api/Controllers/MissionController.cs, backend/api/Controllers/Models/CustomMissionQuery.cs, backend/api/Controllers/Models/ScheduledMissionQuery.cs
This will fix rerunning echo missions
=> Make areaname nullable in queries

frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog.tsx
=> List only robots on selected asset in planner

backend/api/Services/EchoService.cs, backend/api/Services/Models/EchoPoseResponse.cs
=> Fix robot direction in echo missions

frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog.tsx
=> Translate autocomplete placeholder

backend/api.test/EndpointTest.cs, backend/api.test/Mocks/EchoServiceMock.cs, backend/api/Controllers/MissionController.cs
=> Verify asset Id with echo for custom missions

backend/api.test/EndpointTest.cs, backend/api.test/Mocks/EchoServiceMock.cs, backend/api/Controllers/AreaController.cs, backend/api/Services/MissionDefinitionService.cs
=> Add endpoint for getting missions in area

backend/api/Controllers/EchoController.cs, frontend/src/api/ApiCaller.tsx
=> Fix mission dropdown when scheduling echo mission

frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog.tsx, frontend/src/components/Pages/MissionHistoryPage/FilterSection.tsx, frontend/src/components/Pages/RobotPage/LocalizationDialog.tsx
=> Fix dropdowns in frontend

backend/api/EventHandlers/IsarConnectionEventHandler.cs, backend/api/MQTT/MessageModels/IsarRobotHeartbeat.cs, backend/api/MQTT/MessageModels/IsarRobotStatus.cs, backend/api/MQTT/MqttService.cs, backend/api/MQTT/MqttTopics.cs, backend/api/appsettings.Development.json, backend/api/appsettings.Production.json, backend/api/appsettings.Staging.json, backend/api/appsettings.Test.json
Flotilla will now handle the robot status separately from the heartbeat signal. Following https://github.com/equinor/isar/pull/483 ISAR will only publish robot status as an event upon change and not continuously as before.
=> Split status and heatbeat topic event handlers

.github/workflows/backend_lint_and_test.yml, backend/api.test/EndpointTest.cs, backend/api.test/EventHandlers/TestMissionEventHandler.cs, backend/api.test/Mocks/BlobServiceMock.cs, backend/api.test/Mocks/CustomMissionServiceMock.cs, backend/api/Controllers/AreaController.cs, backend/api/Controllers/MissionController.cs, backend/api/Controllers/Models/ScheduleMissionQuery.cs, backend/api/Database/Context/DesignTimeContextFactory.cs, backend/api/Database/Context/InitDb.cs, backend/api/Program.cs, backend/api/Services/AreaService.cs, backend/api/Services/DeckService.cs, backend/api/Services/MissionDefinitionService.cs, backend/api/Services/MissionRunService.cs, backend/api/Services/PlantService.cs, backend/api/Utilities/Exceptions.cs, backend/api/Utilities/PagedList.cs
Fix warnings from pipeline
Fix runtime warnings
Increase pageSize on test to ensure the counting of missions captures needed missions.
Make pipeline fail if there are warnings
Dont merge until https://github.com/equinor/flotilla/pull/967 is merged as many things will change then
=> Fix all warnings and add warning check to pipeline

backend/api.test/Mocks/RobotControllerMock.cs, backend/api/Controllers/EchoController.cs, backend/api/Controllers/RobotController.cs, backend/api/Services/RobotService.cs, backend/api/Utilities/Exceptions.cs, frontend/package-lock.json, frontend/package.json, frontend/src/api/ApiCaller.tsx, frontend/src/components/Header/Header.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/utils/icons.tsx
=> Filter frontend assets by active robots

backend/api/Database/Context/InitDb.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionRestartButton.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx, frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
=> Only show rerun failed missions when applicable

backend/api/Configurations/CustomServiceConfigurations.cs, backend/api/Services/EchoService.cs
The application will now call Echo on behalf of the logged in user rather than on behalf of the application
=> Call echo on behalf of users

.github/workflows/backend_lint_and_test.yml, backend/api.test/EndpointTest.cs, backend/api.test/EventHandlers/TestMissionEventHandler.cs, backend/api.test/Mocks/CustomMissionServiceMock.cs, backend/api.test/Services/MissionService.cs, backend/api.test/Services/RobotService.cs, backend/api.test/api.test.csproj, backend/api/MQTT/MqttService.cs, backend/api/Program.cs, backend/api/Services/CustomMissionService.cs, backend/api/Services/EchoService.cs, backend/api/Services/IsarService.cs, backend/api/Services/SortingService.cs, backend/api/Services/StidService.cs, backend/api/Utilities/AsyncExtensions.cs, backend/api/api.csproj, backend/api/appsettings.Test.json
Update to .net version 7
Update packages accordingly
Smaller code changes to accommodate for .net version 7
=> Update to .net version 7

backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Services/RobotService.cs
To test, might be worth trying to run flotilla, broker and isar-robot to see if behaviour is expected
=> Fix bug where robot and robot model is not properly linked

frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx
=> Validate chosen installation name

frontend/src/components/Contexts/MissionListsContext.tsx
=> Wait to send requests until logged in

frontend/src/components/Pages/InspectionPage/DeckCards.tsx
=> Match deck color with mission colors

backend/api/Controllers/Models/AreaResponse.cs
Fixing mismatch between expected area in frontend and sent areaResponse in backend
=> Fix localization map

frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx, frontend/src/components/Pages/RobotPage/LocalizationDialog.tsx
This PR will also hide all robots if invalid/empty installation
=> Prevent all robots from showing while loading

frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx
=> Fix confirmation button asset page

frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
=> Fix schedule mission button on inpection page

frontend/src/components/Alerts/FailedMissionAlert.tsx, frontend/src/components/Contexts/AlertContext.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx, frontend/src/components/Pages/FrontPage/RobotCards/BatteryStatusView.tsx, frontend/src/components/Pages/FrontPage/RobotCards/PressureStatusView.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx, frontend/src/components/Pages/InspectionPage/DeckCards.tsx, frontend/src/components/Pages/MissionPage/VideoStream/VideoStreamWindow.tsx, frontend/src/language/en.json, frontend/src/utils/MapCompass.tsx
Doesn't fix all the warnings but most of them :)
=> Fix frontend warnings

frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx
=> Filter ongoing and queued missions by installation

frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx
This is a partial fix. Also need to compare to installation filtered missions when deciding if placeholder should show.
=> Fix filtering of missions by installation

frontend/src/components/Contexts/RobotContext.tsx, frontend/src/components/Pages/InspectionPage/DeckCards.tsx, frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx, frontend/src/components/Pages/InspectionPage/InspectionSection.tsx, frontend/src/components/Pages/InspectionPage/InspectionTable.tsx, frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx
Closes #1134 
This PR also includes refactoring to reduce dependencies between components.
=> Show areas in deck cards upon opening the page + refactoring relevant code

backend/api/Controllers/InspectionFindingsController.cs, backend/api/Controllers/Models/InspectionFindingsQuery.cs, backend/api/Database/Models/InspectionFinding.cs, backend/api/Migrations/20231116095346_RefactorInspectionFindingsTable.Designer.cs, backend/api/Migrations/20231116095346_RefactorInspectionFindingsTable.cs, backend/api/Services/InspectionService.cs
=> Refactor inspection findings

.github/workflows/scan_with_trufflehog.yml
Closes robotics-infrastructure Issue:288
=> Add trufflehog github workflow

backend/api/appsettings.json
=> Update interval to 1 day

backend/api/Program.cs, backend/api/appsettings.Local.json
and disable Application Insights Telemetry locally and when debugging
=> Add Local appsettings

backend/api/appsettings.Local.json, frontend/src/api/ApiCaller.tsx, frontend/src/components/Contexts/MissionListsContext.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx
Closes #1181
Also adds frontend error handling when failing to delete a mission
=> Fix mission queue not refreshing upon mission delete

backend/api.test/Client/MissionTests.cs, backend/api.test/Database/DatabaseUtilities.cs, backend/api/Controllers/MissionSchedulingController.cs, backend/api/Database/Models/MissionDefinition.cs, backend/api/Database/Models/MissionRun.cs, backend/api/Migrations/20231219141748_MakeAreaInMissionsRequired.Designer.cs, backend/api/Migrations/20231219141748_MakeAreaInMissionsRequired.cs, backend/api/Services/ActionServices/CustomMissionSchedulingService.cs
=> Make area required in missionRun/Definition

backend/api/Controllers/AreaController.cs, backend/api/Controllers/Models/AreaQueryStringParameters.cs, backend/api/EventHandlers/InspectionFindingEventHandler.cs, backend/api/Services/AreaService.cs
[#1075](https://github.com/equinor/flotilla/issues/1075)
=> Possibility to filter in the Area GET Endpoint

frontend/README.md, frontend/best_practises.md
Closes #1213 although more information can always be added.
=> Add best frontend practises document

frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/ScheduleMissionDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx, frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
Closes #1094 
It also adds alerts for failed missions
=> Add mission placeholder for inspections

backend/api/Controllers/Models/MissionRunQueryStringParameters.cs, backend/api/Services/MissionRunService.cs
=> Filter away localisation/return missions

frontend/src/components/Pages/MissionHistoryPage/HistoricMissionCard.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx, frontend/src/language/no.json
=> Add rerun button to history table

backend/api/Controllers/RobotController.cs
=> Add functionality for resetting robots

frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx
=> Hide alerts in frontpage

backend/api.test/Database/DatabaseUtilities.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Services/MissionRunService.cs
=> Use missionRunResponse in signalr messages

frontend/src/components/Alerts/BlockedRobotAlert.tsx, frontend/src/components/Alerts/FailedMissionAlert.tsx, frontend/src/components/Alerts/FailedSafeZoneAlertContent.tsx, frontend/src/components/Displays/MissionButtons/CreateEchoMissionButton.tsx, frontend/src/components/Displays/MissionDisplays/MissionStatusDisplay.tsx, frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx, frontend/src/components/Pages/MissionHistoryPage/HistoricMissionCard.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx, frontend/src/components/Pages/RobotPage/RobotArmMovement.tsx, frontend/src/components/Styles/StyledComponents.tsx, frontend/src/utils/BackButton.tsx
=> Align buttons' text to the left

.github/workflows/update_aurora_deployment.yml
=> Add quotation marks for commit tag

backend/api.test/Client/AreaTests.cs, backend/api.test/Client/MissionTests.cs
Select always the same robot to
schedule missions on
=> Fix non-deterministic tests

frontend/src/components/Pages/InspectionPage/InspectionTable.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionHeader/MissionDefinitionHeader.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionStyledComponents.tsx
**Result**
**Phone**
**Computer**
=> Mission definition page phone-compatibility

frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
=> Make header cover all objects when scrolling

backend/api/Controllers/ReturnToHomeController.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx
=> Add possibility to returning the robot home in robot page

.github/workflows/deploy_to_development.yml, .github/workflows/update_aurora_deployment.yml
=> Only add quotations in dev

frontend/src/components/Header/Header.tsx
=> Remove unnecessary icons in header

backend/api.test/Mocks/SignalRServiceMock.cs, backend/api/EventHandlers/MissionEventHandler.cs, backend/api/Services/SignalRService.cs, frontend/src/components/Alerts/AlertsBanner.tsx, frontend/src/components/Alerts/FailedAlertContent.tsx, frontend/src/components/Alerts/FailedRequestAlert.tsx, frontend/src/components/Alerts/SafeZoneAlert.tsx, frontend/src/components/Contexts/AlertContext.tsx, frontend/src/components/Contexts/SafeZoneContext.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Improve alert banners

backend/api/Services/MissionDefinitionService.cs
=> Hide deprecated mission definitions

backend/api/EventHandlers/MqttEventHandler.cs
=> Ignore MoveArm step in flotilla

backend/api/Controllers/RobotController.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/RobotService.cs
=> Refactor set robot to unavailable function

backend/api/EventHandlers/IsarConnectionEventHandler.cs
Closes #1488 
This PR will become more useful when https://github.com/equinor/flotilla/pull/1494 and https://github.com/equinor/flotilla/pull/1490 merges.
=> Do not update robot status on timeout

frontend/src/components/Displays/RobotDisplays/BatteryStatusDisplay.tsx
=> Avoid zero battery being intepreted as null

backend/api.test/Mocks/SignalRServiceMock.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/EventHandlers/TeamsMessageEventHandler.cs, backend/api/MQTT/MessageModels/IsarCloudHealth.cs, backend/api/MQTT/MqttService.cs, backend/api/MQTT/MqttTopics.cs, backend/api/Program.cs, backend/api/Services/Events/MissionEventArgs.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/SignalRService.cs, backend/api/Services/TeamsMessageService.cs, backend/api/appsettings.Development.json, backend/api/appsettings.Local.json, backend/api/appsettings.Production.json, backend/api/appsettings.Staging.json, backend/api/appsettings.Test.json, frontend/src/components/Contexts/AlertContext.tsx, frontend/src/components/Displays/ConfirmScheduleDialogs/LocalizationVerification/ConfirmLocalizationDialog.tsx, frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx
Closes [#356](https://github.com/equinor/isar-taurob/issues/356)
=> Monitor system status

backend/api.test/EventHandlers/TestMissionEventHandler.cs, backend/api.test/Mocks/SignalRServiceMock.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/ReturnToHomeService.cs, backend/api/Services/SignalRService.cs
=> Move arm triggers banner failed return home

frontend/src/components/Displays/MissionButtons/MissionControlButtons.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/Task.ts
=> Fix stop ongoing mission dialogs

backend/api/Controllers/MissionSchedulingController.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/RobotService.cs
=> Improve start missions with pressure/battery value

backend/api.test/EventHandlers/TestMissionEventHandler.cs, backend/api.test/Mocks/StidServiceMock.cs, backend/api/Services/MissionDefinitionService.cs, backend/api/Services/SourceService.cs, backend/api/Services/StidService.cs
=> Remove unused variable

backend/api/Services/Models/IsarMissionDefinition.cs
This removes the need for a localisation mission.
=> Send localisation pose to ISAR in mission

backend/api/Controllers/MissionSchedulingController.cs, backend/api/Database/Models/Robot.cs, backend/api/Services/ActionServices/CustomMissionSchedulingService.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Utilities/Exceptions.cs
The PR also refactors custom mission pre-checks and adds a pre-check for high pressure.
=> Add a common mission pre-check function

frontend/src/components/Displays/ConfirmScheduleDialogs/LocalizationVerification/ScheduleMissionStyles.tsx, frontend/src/utils/DeckMapView.tsx
=> Fix buttons disappearing on long maps

frontend/src/components/Contexts/SignalRContext.tsx
=> Prevent frontend from crashing on empty signalR message

backend/api.test/Mocks/StidServiceMock.cs, backend/api/Controllers/MissionSchedulingController.cs, backend/api/Services/StidService.cs
=> Allow echo missions with tags without area code

backend/api/EventHandlers/MqttEventHandler.cs
This reverts commit 786c8138591b0e1307b3e0df64fd51c61e334e1b.
=> Revert "Add update robot semaphore"

frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx
=> Change rerun mission button

frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx, frontend/src/components/Pages/MissionHistoryPage/HistoricMissionCard.tsx, frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Change rerun buttons

backend/api/Services/MissionRunService.cs
=> Fix removing a mission from queue that has started

frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx
=> Filter robots by available or busy status

backend/api/EventHandlers/IsarConnectionEventHandler.cs
=> Trigger robot available when robot comes online

backend/api/Services/MissionDefinitionService.cs
=> Fix last successful mission run update

frontend/src/components/Contexts/AlertContext.tsx, frontend/src/components/Contexts/InstallationContext.tsx, frontend/src/components/Contexts/MissionDefinitionsContext.tsx, frontend/src/components/Contexts/MissionRunsContext.tsx, frontend/src/components/Contexts/RobotContext.tsx, frontend/src/components/Contexts/SafeZoneContext.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusSection.tsx, frontend/src/components/Pages/InspectionPage/DeckCards.tsx, frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx, frontend/src/components/Pages/InspectionPage/InspectionSection.tsx, frontend/src/components/Pages/InspectionPage/InspectionTable.tsx, frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
=> Move installation filtering to contexts

frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx, frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
Follow-up #1677, adding filter on ScheduleMissionDialogs.tsx
=> Filtering robots in ScheduleMissionDialogs.tsx

frontend/src/components/Displays/ConfirmScheduleDialogs/LocalizationVerification/ScheduleMissionWithLocalizationVerification.tsx
=> Fix dialogs during ongoing localization mission

backend/api/Services/MissionDefinitionService.cs
=> Fix filtering by missiondefinition name

backend/api.test/Client/MissionTests.cs, backend/api/Controllers/MissionLoaderController.cs, backend/api/Controllers/MissionSchedulingController.cs, backend/api/Controllers/Models/ScheduledMissionQuery.cs, backend/api/Program.cs, backend/api/Services/EchoService.cs, backend/api/Services/MissionLoaders/EchoAndCustomMissionLoader.cs, backend/api/Services/MissionLoaders/EchoMissionLoader.cs, backend/api/Services/SourceService.cs, backend/api/appsettings.json, frontend/src/api/ApiCaller.tsx
=> Fix custom missions

backend/api/Services/MissionLoaders/EchoMissionResponse.cs
to match an update coming from echo
=> Adjust data model for echo api call

backend/.config/dotnet-tools.json, backend/api.test/Client/MissionTests.cs
=> Attempt to fix tests that sometimes throws unexpected Exception

frontend/src/components/Displays/ConfirmScheduleDialogs/ConfirmScheduleDialog.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
=> Fix visualization of pressure when 0mBar

backend/api/Services/RobotService.cs
Closes #1359 
Previously we were sending signalR messages that the robot had been updated with isarConnected being changed, but since the robotModel was null we were ignoring it in the frontend. This was occuring since we were not including the robot model in the database query we used when updating isarConnected. When I changed this to include the robot model we got an error since the ExecuteUpdateAsync function does not allow SQL JOINS (see https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete#navigations-and-related-entities). I therefore normalised the code to use the context.Update function like we do in the rest of the RobotService. The only place that still uses ExecuteUpdateAsync is the UpdateRobotPose function as this one does not suffer from the same …
=> Fix flotilla not reporting connection issues after broker goes down

frontend/src/components/Displays/RobotDisplays/BatteryStatusDisplay.tsx, frontend/src/components/Displays/RobotDisplays/PressureStatusDisplay.tsx, frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx, frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx
Updated based on feedback from ux designer
=> Update robot status icons, colour and fontsize

backend/api/Services/MissionRunService.cs, backend/api/Services/RobotService.cs
=> Change log level to debbug

backend/api.test/api.test.csproj, backend/api/api.csproj, frontend/package-lock.json
=> Run npm audit fix

backend/api/Database/Models/Inspection.cs, backend/api/Migrations/20241213081436_AddIsarInspectionIdToInspections.Designer.cs, backend/api/Migrations/20241213081436_AddIsarInspectionIdToInspections.cs, backend/api/Services/Models/IsarMissionDefinition.cs, backend/api/Services/Models/IsarStartMissionResponse.cs, backend/api/Services/Models/IsarTask.cs
=> Set inspection id from isar response

backend/api/Services/InspectionService.cs
=> Call IDA in behalf of the app

backend/api/Services/InspectionService.cs
=> Revert call IDA using app

backend/api/Services/MissionSchedulingService.cs
=> Log if missionrun has no inspection area

backend/api/Controllers/MissionSchedulingController.cs
=> Log if mission definition has no deck

backend/api/Controllers/MissionSchedulingController.cs
=> Add logs when mission definition has no deck

backend/api/EventHandlers/MqttEventHandler.cs
=> Avoid maintaining lingering database requests in MQTT event handler

backend/api.test/Mocks/BlobServiceMock.cs, backend/api.test/Mocks/MapServiceMock.cs, backend/api/Controllers/InspectionController.cs, backend/api/Controllers/MapController.cs, backend/api/Services/BlobService.cs, backend/api/Services/InspectionService.cs, backend/api/Services/MapService.cs
=> Add exception handling to blob store interactions

backend/api/EventHandlers/InspectionFindingEventHandler.cs, backend/api/EventHandlers/TeamsMessageEventHandler.cs
The only functional code change is that it no longer logs successes and an error was turned into a warning.
=> Refactor inspection findings/teams code

backend/api/api.csproj
=> Snyk security upgrade Microsoft.Identity.Web from 3.0.0 to 3.3.0

backend/api/appsettings.json
=> Increase time out for isar disconnect

backend/api/Services/InspectionService.cs
=> Call IDA as an app

frontend/Dockerfile
=> Adapt docker build to vite

frontend/Dockerfile, frontend/run_nginx.sh
=> Add run_nginx check to see if file is found

frontend/Dockerfile, frontend/index.html
=> Change path used to reference manifest

frontend/index.html
=> Fetch manifest from public folder

frontend/index.html
=> Fetch from public in index

frontend/index.html
=> Change path to reference index.tsx

frontend/index.html, frontend/vite.config.ts
=> Change base url

frontend/index.html
=> Run nginx check

backend/api/Controllers/Models/MissionRunQueryStringParameters.cs, backend/api/Controllers/ReturnToHomeController.cs, backend/api/Database/Models/MissionRun.cs, backend/api/Database/Models/MissionTask.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/ReturnToHomeService.cs
=> Unify return to home and docking naming

frontend/src/components/Displays/MissionButtons/MissionControlButtons.tsx
=> Fix nested buttons

frontend/src/components/Pages/InspectionReportPage.tsx/InspectionView.tsx
Updated copy of https://github.com/equinor/flotilla/pull/1916 (I do not have permission to push to his fork).
=> Add constant string to use query key

backend/api/Controllers/MissionSchedulingController.cs
=> Fetch mission definition map info if null

backend/api/Services/MissionSchedulingService.cs
=> Avoid scheduling dock mission twice in parallell

backend/api/Controllers/MissionSchedulingController.cs
=> Try to assign map to mission if no existing map

frontend/src/components/Displays/ConfirmScheduleDialogs/ConfirmScheduleDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/RobotModel.ts, frontend/src/utils/IsRobotReadyToRunMissions.tsx
=> Display reason for robot not running mission

frontend/src/components/Pages/RobotPage/ReturnHomeButton.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx
=> Prevent spam-click of return home button

backend/api/Services/RobotModelService.cs
=> Fix typo for context in robotmodelservice

backend/api/Services/MissionRunService.cs
=> Update inspections after isar mission accepted

backend/api.test/Controllers/MissionSchedulingControllerTests.cs
=> Add time delay to failing test

frontend/src/components/Pages/InspectionReportPage/InspectionStyles.tsx, frontend/src/components/Pages/InspectionReportPage/InspectionView.tsx
=> Contain inspection image in dialog

backend/api/Database/Models/Inspection.cs, backend/api/Database/Models/Robot.cs, backend/api/MQTT/MessageModels/IsarTask.cs, backend/api/Services/EchoService.cs, backend/api/Services/Models/IsarTask.cs, frontend/src/models/Robot.ts
=> Support gas measurement inspection

backend/api/Services/EchoService.cs
=> Fix problem of duplicate robot poses

backend/api/Controllers/MissionSchedulingController.cs
=> Fix that scheduling fails if no map

frontend/src/models/Inspection.ts
=> Add thermal image to supported inspection types

.github/workflows/stale.yml
=> Remove stale comments

frontend/src/language/en.json, frontend/src/language/no.json
=> Remove outdated popup text

backend/api/appsettings.Local.json
=> Revert to default devUserID

backend/api/Database/Models/Robot.cs, backend/api/Services/LocalizationService.cs, frontend/src/models/Robot.ts
Depends on: https://github.com/equinor/isar-anymal/pull/175
=> Remove deprecated auto-localize

backend/api/Controllers/InspectionController.cs
=> Fix get inspection endpoint

frontend/src/components/Displays/MissionButtons/MissionControlButtons.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Rename stop button to skip

frontend/src/components/Pages/InspectionPage/InspectionTable.tsx
=> Fix add to queue button

backend/api/Services/RobotService.cs
=> Filter away deprecated robots in robotservice

backend/api/Services/InspectionAreaService.cs
=> Log warning for tasks outside area polygon

backend/api/appsettings.json
=> Edit hangfire logging settings

backend/api/Controllers/MissionSchedulingController.cs, backend/api/Database/Models/MissionTask.cs
=> Fix tasks already being completed upon scheduling

backend/api/Services/MissionSchedulingService.cs
=> Fix return to home not running on low battery

backend/api.test/Mocks/SignalRServiceMock.cs, backend/api/HostedServices/InspectionFrequencyHostedService.cs, backend/api/Services/SignalRService.cs, frontend/src/components/Alerts/FailedAlertContent.tsx, frontend/src/components/Contexts/AlertContext.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Add auto scheduling fail banner to notify the user

frontend/src/components/NavigationMenu/NavigationMenu.tsx, frontend/src/components/NavigationMenu/NavigationMenuPages.tsx, frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/RobotCards/RobotStatusCard.tsx, frontend/src/components/Pages/RobotCards/RobotStatusSection.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Reintroduce robot cards

frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx, frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
=> Fix add mission to queue dialogs

frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx, frontend/src/utils/StringFormatting.tsx
=> Capitalize first letter of auto schedule table

.github/workflows/notifyPossibleMigrationUpdate.yml, .github/workflows/verifyMigrations.yml
=> Change tj-actions to version without security issue

backend/api/Services/MissionDefinitionService.cs, frontend/src/components/Alerts/BlockedRobotAlert.tsx, frontend/src/components/Alerts/DockAlert.tsx, frontend/src/components/Alerts/FailedAlertContent.tsx, frontend/src/components/Alerts/FailedMissionAlert.tsx, frontend/src/components/Alerts/FailedRequestAlert.tsx, frontend/src/components/Pages/DefaultPage/DefaultPage.tsx, frontend/src/components/Pages/InspectionPage/InspectionAreaCards.tsx, frontend/src/components/Pages/InspectionPage/InspectionTable.tsx, frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionStyledComponents.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/components/Pages/MissionPage/MissionPage.tsx, frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx, frontend/src/components/Pages/MissionPage/TaskTableAndMap.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx, frontend/src/components/Styles/StyledComponents.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/MissionDefinitionUpdateForm.ts
=> Improve mission definition page

frontend/src/components/Pages/RobotPage/PressureTable.tsx, frontend/src/components/Pages/RobotPage/ReturnHomeButton.tsx, frontend/src/components/Pages/RobotPage/RobotArmMovement.tsx, frontend/src/components/Pages/RobotPage/RobotPage.tsx
=> Improve robot page

frontend/src/components/Contexts/MissionRunsContext.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/Mission.ts
=> Add ongoing mission info in tab header

frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx
=> Allow redirect to specific tab using tabname in URL

backend/api/Controllers/MissionSchedulingController.cs, backend/api/Services/MissionDefinitionService.cs, backend/api/Services/MissionSchedulingService.cs, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx
=> Show map on missionDefinitionPage even if no robot

frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/RobotCard.tsx
=> Align buttons on missionControlCard

frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Add view mission definition button

backend/api/Database/Context/InitDb.cs
=> Add placebot with default inspectionArea

frontend/src/components/Pages/InspectionPage/InspectionAreaCards.tsx, frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx, frontend/src/components/Pages/InspectionPage/InspectionSection.tsx, frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionHeader/MissionDefinitionHeader.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionStyledComponents.tsx
=> Refactor style dictionaries

backend/api/Database/Models/AutoScheduleFrequency.cs, backend/api/Migrations/20250325071437_RenameTimesOfDay.Designer.cs, backend/api/Migrations/20250325071437_RenameTimesOfDay.cs, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/MissionDefinitionPage/EditAutoScheduleDialogContent.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/src/models/AutoScheduleFrequency.ts
=> Rename TimesOfDay to reflect timezone

frontend/src/components/Alerts/DockAlert.tsx, frontend/src/components/Displays/InspectionAreaVerificationDialogs/ScheduleMissionWithInspectionAreaVerification.tsx, frontend/src/components/Displays/RobotDisplays/BatteryStatusDisplay.tsx, frontend/src/components/Displays/RobotDisplays/PressureStatusDisplay.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/FetchingMissionsDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/NoMissionsDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/ScheduleMissionDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx, frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx, frontend/src/utils/IsRobotReadyToRunMissions.tsx, frontend/src/utils/MapCompass.tsx
=> Remove unsupported type hinting

frontend/src/components/Pages/FrontPage/FrontPage.tsx
=> Wrap tabs if too small screen

frontend/src/components/Alerts/AlertsListItem.tsx, frontend/src/components/Header/AlertIcon.tsx
=> Improve alerts list

frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
=> Avoid button overflow

backend/api/Controllers/MissionRunController.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Add remove missions in the queue button

backend/api.test/Database/DatabaseUtilities.cs, backend/api.test/HostedServices/TestAutoSchedulingHostedService.cs, backend/api/HostedServices/AutoSchedulingHostedService.cs
=> Add auto scheduler test

frontend/package-lock.json, frontend/package.json
=> Upgrade npm packages

backend/api.test/Database/DatabaseUtilities.cs, backend/api.test/Mocks/MissionLoaderMock.cs, backend/api/Controllers/MissionDefinitionController.cs, backend/api/Controllers/MissionSchedulingController.cs, backend/api/Controllers/Models/MissionDefinitionResponse.cs, backend/api/Controllers/Models/PlantInfo.cs, backend/api/Program.cs, backend/api/Services/EchoService.cs, backend/api/Services/InstallationService.cs, backend/api/Services/MissionDefinitionService.cs, backend/api/Services/MissionDefinitionTaskService.cs, backend/api/Services/MissionLoaders/CustomMissionLoader.cs, backend/api/Services/MissionLoaders/EchoAndCustomMissionLoader.cs, backend/api/Services/MissionLoaders/EchoMissionLoader.cs, backend/api/Services/MissionLoaders/MissionLoaderInterface.cs
=> Add custom mission loader

.github/workflows/notifyPossibleMigrationUpdate.yml, .github/workflows/verifyMigrations.yml
=> Change tj-actions version

backend/api.test/Controllers/InspectionAreaControllerTests.cs
=> Fix failing test on windows

backend/api/Services/MissionSchedulingService.cs
=> Update outdated log message

backend/api/api.csproj, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx, frontend/src/components/Pages/InspectionPage/InspectionTable.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionStyledComponents.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Add auto schedule button

backend/api/api.csproj
=> Fix mixing of Identity.Web versions

backend/api/Controllers/InspectionController.cs
=> Reduse logging when no inspection result exist

backend/api/Controllers/EmergencyActionController.cs, backend/api/EventHandlers/MissionEventHandler.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Services/Events/MissionEventArgs.cs, backend/api/Services/MissionSchedulingService.cs
=> Provide stop reason for aborted/cancelled missions

backend/api/Services/EchoService.cs
=> Call echo as app

frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx
=> Correct displayed home and recharging status

backend/api/HostedServices/AutoSchedulingHostedService.cs, backend/api/Services/MissionSchedulingService.cs
=> Use source for auto schedule

backend/api.test/Database/DatabaseUtilities.cs, backend/api.test/Mocks/SignalRServiceMock.cs, backend/api/Controllers/MissionDefinitionController.cs, backend/api/Controllers/Models/UpdateMissionDefinitionQuery.cs, backend/api/Database/Models/AutoScheduleFrequency.cs, backend/api/HostedServices/AutoSchedulingHostedService.cs, backend/api/Migrations/20250509095804_AddAutoScheduledJobs.Designer.cs, backend/api/Migrations/20250509095804_AddAutoScheduledJobs.cs, backend/api/Program.cs, backend/api/Services/AutoScheduleService.cs, backend/api/Services/MissionDefinitionService.cs, backend/api/Services/SignalRService.cs, frontend/src/api/ApiCaller.tsx, frontend/src/components/Alerts/FailedAlertContent.tsx, frontend/src/components/Alerts/InfoAlertContent.tsx, frontend/src/components/Contexts/AlertContext.tsx, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx, frontend/src/components/Pages/MissionDefinitionPage/EditAutoScheduleDialogContent.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/AutoScheduleFrequency.ts
=> New skip auto missions

backend/api/Controllers/MissionDefinitionController.cs
=> Fix skip auto schedule endpoint

backend/api/Database/Models/Robot.cs, backend/api/EventHandlers/MqttEventHandler.cs
=> Fix battery checks

frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/InspectionPage/InspectionTable.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Enable schedule of first auto mission and add cancel button to auto scheduling page

backend/api/Controllers/MissionDefinitionController.cs, backend/api/HostedServices/AutoSchedulingHostedService.cs, backend/api/Services/MissionDefinitionService.cs
=> Fix unremoved next auto schedule

backend/api.test/Database/DatabaseUtilities.cs, backend/api/Controllers/MissionDefinitionController.cs, backend/api/Controllers/Models/UpdateMissionDefinitionQuery.cs, backend/api/HostedServices/AutoSchedulingHostedService.cs, backend/api/Services/AutoScheduleService.cs, backend/api/Services/MissionDefinitionService.cs
=> Start new jobs on changed autoScheduleFrequency

frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Show today first in auto schedule tab

backend/api/Database/Models/Robot.cs, backend/api/EventHandlers/MissionEventHandler.cs, backend/api/EventHandlers/MqttEventHandler.cs
=> Fix mission starting on pressure update

backend/api/Services/InspectionService.cs
=> Update sara endpoint path

backend/api/Database/Models/AutoScheduleFrequency.cs, backend/api/HostedServices/AutoSchedulingHostedService.cs, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleMissionTableRow.tsx, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/FrontPage/AutoScheduleSection/NextAutoScheduleMissionView.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx, frontend/src/components/Pages/MissionDefinitionPage/EditAutoScheduleDialogContent.tsx, frontend/src/language/en.json, frontend/src/language/no.json, frontend/src/models/AutoScheduleFrequency.ts
=> Display completed and skipped missions as disabled

frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
=> Remove commented out styling

backend/api.test/Controllers/InspectionAreaControllerTests.cs, backend/api/Controllers/Models/CustomMissionQuery.cs, backend/api/Database/Models/Inspection.cs, backend/api/Migrations/20250528125518_RemoveAnalysisType.Designer.cs, backend/api/Migrations/20250528125518_RemoveAnalysisType.cs, frontend/src/models/Inspection.ts
this is now interpreted based on the InspectionDescription
Needs migrations
=> Remove unused AnalysisType

frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx
=> Fix useQuery function

frontend/src/components/Contexts/MissionRunsContext.tsx, frontend/src/components/Displays/InspectionAreaVerificationDialogs/ConflictingInspectionAreaDialog.tsx, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleCalendar.tsx, frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx, frontend/src/components/Pages/FrontPage/AutoScheduleSection/NextAutoScheduleMissionView.tsx, frontend/src/components/Pages/MissionDefinitionPage/EditAutoScheduleDialogContent.tsx, frontend/src/components/Pages/RobotCards/RobotStatusSection.tsx
=> Implement typescript code quality recommendations from snyk

backend/api/Controllers/RobotController.cs, backend/api/Utilities/SanitizeInput.cs, backend/api/api.csproj
=> Prevent log forging from inputed armPosition

.github/workflows/notifyPossibleMigrationUpdate.yml, .github/workflows/verifyMigrations.yml
=> Bump tj-actions/changed-files version

frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleCalendar.tsx
=> Adjust end of calendar event

backend/api/Controllers/RobotController.cs, backend/api/Database/Models/MissionRun.cs, backend/api/EventHandlers/MissionEventHandler.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/Models/IsarMissionDefinition.cs
=> Reuse missionRun when interupted and resumed

broker/mosquitto/config/access_control
=> Only one user called sara in broker access control

backend/api.test/Database/DatabaseUtilities.cs, backend/api/Controllers/Models/MissionRunResponse.cs, backend/api/Database/Models/MissionRun.cs, backend/api/Migrations/20250616112006_MakeMissionIdInMissionRunRequired.Designer.cs, backend/api/Migrations/20250616112006_MakeMissionIdInMissionRunRequired.cs, frontend/src/models/Mission.ts
=> Make missionId in missionRun required

backend/api/EventHandlers/MqttEventHandler.cs, backend/api/MQTT/MessageModels/IsarMission.cs
=> Display isar failure reason on missions

frontend/src/language/en.json, frontend/src/language/no.json
=> Add missing translation

backend/api/Services/MissionSchedulingService.cs
=> Fix sending of stopMission when no mission

backend/api/EventHandlers/MqttEventHandler.cs, backend/api/MQTT/MessageModels/IsarStartup.cs, backend/api/MQTT/MqttService.cs, backend/api/MQTT/MqttTopics.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/appsettings.Development.json, backend/api/appsettings.Local.json
Dependent on: https://github.com/equinor/isar/pull/838
=> Reschedule missionRun if isar instance restarted

frontend/package-lock.json, frontend/package.json, frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx, frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx, frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/vite.config.ts
=> Fix refreshing issues

frontend/package-lock.json, frontend/package.json, frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx, frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx, frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/vite.config.ts
=> Revert fix refresh frontend

frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleMissionTableRow.tsx
=> Add description to auto schedule view

frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx
=> Test fix refreshing issues

frontend/src/components/Alerts/AlertStyles.tsx, frontend/src/components/Alerts/BlockedRobotAlert.tsx, frontend/src/components/Alerts/DockAlert.tsx, frontend/src/components/Alerts/FailedAlertContent.tsx, frontend/src/components/Alerts/FailedMissionAlert.tsx, frontend/src/components/Alerts/FailedRequestAlert.tsx, frontend/src/components/Alerts/InfoAlertContent.tsx
=> Fix style variations on banners

frontend/src/components/Alerts/FailedMissionAlert.tsx, frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx, frontend/src/components/NavigationMenu/NavigationMenu.tsx, frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx, frontend/src/components/Pages/FlotillaSite.tsx, frontend/src/components/Pages/FrontPage/FrontPage.tsx, frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx, frontend/vite.config.ts
=> Fix tab URLs

frontend/vite.config.ts
=> Undo improvement in routing

frontend/src/components/Header/Header.tsx, frontend/src/components/Pages/FlotillaSite.tsx
=> Revert hash routing

frontend/src/components/Pages/FlotillaSite.tsx
=> Test URL refreshing

frontend/src/components/Pages/FlotillaSite.tsx
=> Revert test of URL refreshing

backend/api.test/Mocks/HttpContextAccessorMock.cs, backend/api/Services/AccessRoleService.cs, backend/api/Utilities/HttpContextExtensions.cs
=> Replace accessRole check with IsInRole

broker/mosquitto/config/mosquitto.conf
=> Improve timestamp in broker logs

backend/api/Database/Models/Inspection.cs, backend/api/Database/Models/MissionTask.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Migrations/20250722082429_RemoveInspectionStatus.Designer.cs, backend/api/Migrations/20250722082429_RemoveInspectionStatus.cs, backend/api/Services/EchoService.cs, backend/api/Services/InspectionService.cs, backend/api/Services/MissionRunService.cs, frontend/src/models/Inspection.ts
=> Remove inspection status

frontend/src/components/Alerts/AlertsListItem.tsx, frontend/src/components/Header/AlertIcon.tsx
=> Improve alert list

backend/api.test/Security/AuthenticationControllerTests.cs, backend/api.test/TestNoAuthWebApplicationFactory.cs, backend/api.test/TestSetupHelpers.cs
=> Add tests for auth

frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx, frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx, frontend/src/language/en.json, frontend/src/language/no.json
=> Add "xx missions in queue"-button

backend/api/Services/MissionSchedulingService.cs
=> Give feedback if no inspection area for robot

.github/workflows/scan_with_trufflehog.yml
=> Improve TruffleHog scan

.github/workflows/scan_with_trufflehog.yml
=> Remove fail flag for TruffleHog

frontend/src/components/Pages/FrontPage/FrontPage.tsx
The issue was that @equinor/eds-core-react kept Tabs.Panel mounted even when hidden, so MissionStats and other tab components remained active and continued fetching data in the background (every 1 second).
The solution was to remove <Tabs.Panels> and render only the active tab’s component via {tabs[activeIndex]?.render()}, which unmounted inactive content and stopped unnecessary requests.
This PR will reduce the amount of backend and database calls made by users just having the flotilla frontend open.
=> Remove api calls for tab-components that are not viewed

backend/api.test/Database/DatabaseUtilities.cs, backend/api.test/EventHandlers/TestMissionEventHandler.cs, backend/api.test/Utilities/TestObjectGenerator.cs, backend/api/Controllers/Models/MissionRunResponse.cs, backend/api/Database/Models/MissionRun.cs, backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Services/MissionRunService.cs, backend/api/Services/MissionSchedulingService.cs, backend/api/Services/Models/IsarMissionDefinition.cs, frontend/src/models/Mission.ts
Dependent on https://github.com/equinor/isar/pull/840
=> Assume isarMissionId is identical to mission.Id

frontend/src/components/Contexts/MissionRunsContext.tsx
=> Debug ongoing missions signalr update frontend

backend/api/EventHandlers/MqttEventHandler.cs, backend/api/Services/MissionRunService.cs, backend/api/Services/MissionSchedulingService.cs
=> Remove unnecessary null checks

backend/api/Controllers/InspectionController.cs, backend/api/Services/InspectionService.cs, backend/api/Utilities/Exceptions.cs
=> Add logs when inspection is not found

.github/workflows/runMigrations.yml
=> Add tenant id to workflow

backend/api/Program.cs, frontend/src/components/Contexts/SignalRContext.tsx
=> Allow server sent events in signalr

config/otel-collector-config.yaml
=> Keep all traces for all status codes

backend/api/Controllers/RobotController.cs
=> Allow users to release intervention needed

backend/api/Program.cs
=> Reintroduce https for swagger

backend/api/appsettings.Development.json
=> Fix dev pointilla scope

frontend/src/components/Pages/MissionPage/MapPosition/PointillaMapView.tsx
=> Fix pointilla maps

frontend/src/components/Pages/MissionPage/MapPosition/PointillaMapView.tsx
=> Improve map design

backend/api/appsettings.Production.json, backend/api/appsettings.Staging.json
=> Connect to pointilla prod

frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx
=> Fix auto scheduling remounting
