- README.md
- broker/Dockerfile
- broker/README.md
- broker/mosquitto/config/mosquitto.conf
- broker/mosquitto/config/passwd_file
- broker/mosquitto/log/.gitignore
- docker-compose.yml
> Add mqtt broker

- backend/Dockerfile
- docker-compose.yml
added Dockerfile and update docker-compose.yml
> Backend dockerfile

- backend/src/flotilla/api/events_api.py
- backend/src/flotilla/api/robots_api.py
- backend/src/flotilla/database/crud.py
- backend/src/flotilla/database/models.py
- backend/src/flotilla/main.py
- backend/tests/test_api/test_events_api.py
> Add events api

- backend/src/flotilla/api/events_api.py
- backend/src/flotilla/database/crud.py
- backend/src/flotilla/database/models.py
- backend/tests/test_api/test_events_api.py
- backend/tests/test_crud.py
> Add check for conflicting events before creation

- backend/api.test/TestRobotController.cs
- backend/api/Context/FlotillaDbContext.cs
- backend/api/Database/Models/IsarStep.cs
- backend/api/Database/Models/IsarTask.cs
- backend/api/Database/Models/Report.cs
- backend/api/Database/Models/Step.cs
- backend/api/Database/Models/Task.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/MQTT/MessageModels/IsarMission.cs
- backend/api/MQTT/MessageModels/IsarStep.cs
- backend/api/MQTT/MessageModels/IsarTask.cs
- backend/api/MQTT/MqttService.cs
- backend/api/MQTT/MqttTopics.cs
- backend/api/Models/IsarStartMissionResponse.cs
- backend/api/Program.cs
- backend/api/Services/EchoService.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/ReportService.cs
> Update report on events

- backend/Dockerfile
- backend/README.md
- backend/api/Configurations/ConfigurationBuilderExtensions.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Program.cs
- backend/api/Services/ReportService.cs
- backend/backend.sln
- docker-compose.yml
> Bug - backend dockerization

- backend/api/MQTT/MqttService.cs
- backend/api/appsettings.Development.json
- broker/README.md
Closes #229 
The current implementation causes flotilla backend to simply stop if the broker cannot be reached within the attempt limit.
This can be disabled by changing the config variable `ShouldFailOnMaxRetries`.
This was done because the backend is reliant on being connected to the broker for it to function as intended, and if it can't reach the broker, which is on the same docker compose network, then this implies that something is very wrong.
Not sure about this, though, and I'm very open for discussion.
> Bug mqtt infinite retries

- backend/api.test/TestRobotController.cs
- backend/api/Context/InitDb.cs
- backend/api/Controllers/RobotController.cs
- backend/api/Database/Models/Robot.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/EventHandlers/ScheduledMissionEventHandler.cs
- backend/api/MQTT/MessageModels/IsarConnect.cs
- backend/api/MQTT/MqttService.cs
- backend/api/MQTT/MqttTopics.cs
- backend/api/Services/IsarService.cs
- backend/api/appsettings.Development.json
- backend/api/appsettings.Production.json
Solves #247 and solves #263
This PR does two things:
1. Makes sure a that there is one robot in the database corresponding to the connected instances of ISAR. Currently, the `name` of the robot, stored as `robot.Name` in flotilla and `robotId` in ISAR is the unique identifier. The `host` and `port` for each robot is fetched from ISAR. Whether assigning `host` and `port` should be the responsibility of ISAR and flotillla is up for discussion. 
1. Allows for several ISAR instances /robots to be connected and monitored to flotilla. By making sure that each robot is assigned to an ISAR instance and that it has the updated ISAR api connection info `robot.Host` and `robot.Port`, the general `_isarUri` config is removed and a url is generated for each robot.
The robot in the database should also …
> Update robot when ISAR connects

- backend/api.test/DbContextTestSetup.cs
- backend/api.test/Services/ReportService.cs
- backend/api.test/Services/RobotService.cs
- backend/api.test/Services/ScheduledMissionService.cs
- backend/api.test/TestRobotController.cs
- backend/api.test/TestScheduledMissionController.cs
- backend/api/Configurations/CustomServiceConfigurations.cs
- backend/api/Controllers/Models/CreateReportQuery.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Context/InitDb.cs
- backend/api/Database/Models/Report.cs
- backend/api/Program.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/ReportService.cs
- backend/api/Services/RobotService.cs
- backend/api/Services/ScheduledMissionService.cs
- backend/api/api.csproj
- backend/api/appsettings.Development.json
- backend/api/appsettings.json
Change test / dev database to SQLite. 
Add possibility to connect to remote SQL database.
Update tests and usage of database in tests
> Use sqlite inmemory database

- backend/api/EventHandlers/MqttEventHandler.cs
This error logging was just ment for dev as there is a of logging happening and hard to find those lines you are looking for. Reducing the logging of mqtt messages and frequent status updates should be considered to get a more readable log with less spam. See #273
> Remove dev logging

- backend/api/Services/RobotService.cs
Entity framework can not translate string comparison details for SQL calls to database, so this leads to a runtime error.
> Remove string comparison for SQL calls

- backend/README.md
- backend/api/MQTT/MqttService.cs
Mainly changed the naming of secrets in our keyvault according to [docs](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0#secret-storage-in-the-production-environment-with-azure-key-vault),
using `--` as the section delimiter for ASP.NET to properly attribute the correct secret to the corresponding config value.
Did the same for MQTT password and updated readme accordingly.
> Change expected secret format from keyvault

- .editorconfig
- backend/api/Controllers/RobotController.cs
- backend/api/Services/IsarService.cs
Resolves #278 by disabling a robot in the database whenever an API POST request using `IsarService` throws an `HttpRequestException`, indicating that the corresponding ISAR instance is unavailable. At once, the robot status is also set to `Offline`.
The `HttpRequestException` is caught for all endpoints involving `IsarService` and the error reported, which fixes #255.
> Disable robot if ISAR connection is lost

- .github/workflows/publish_docker_image.yml
- broker/Dockerfile
- broker/README.md
- broker/entrypoint.sh
- setup.sh
This means an environment variable TLS_SERVER_KEY is required to start the broker docker container. Thus the certificate key is not stored in the image itself and not retrievable if the image is lost.
The image may now be published publicly.
> Set broker certificate based on environment

- broker/entrypoint.sh
Fix where in some cases server key is created with single quotes
> Remove single quotes from server key

- .github/workflows/publish_docker_image.yml
`login-server` was from an example and it looks like it is replaced by the `registry` keyword and hence can be removed.
Got this from the logs:
`Warning: Unexpected input(s) 'login-server', valid inputs are ['registry', 'username', 'password', 'ecr', 'logout']`
> Remove wrong keyword in deploy workflow

- .github/workflows/notifyPossibleMigrationUpdate.yml
- backend/README.md
- backend/api/Configurations/ConfigurationBuilderExtensions.cs
- backend/api/Database/Context/DesignTimeContextFactory.cs
The design time Db Context builder will ensure that we always use the correct database connection strings from the keyvault when adding migrations and updating the database.
> Design time db context

- backend/api/Controllers/MissionController.cs
- backend/api/Services/EchoService.cs
- backend/api/Services/StidService.cs
It is no longer required to configure installations code in the backend. This is provided through the API from the frontend as the use selects which installation they are on. 
Closes #627
> Use dynamic installation code rather than config

- .github/workflows/notifyPossibleMigrationUpdate.yml
- .github/workflows/verifyMigrations.yml
The newest version caused these pipelines to crash
> Lock action versions

- frontend/src/components/Pages/FrontPage/MissionOverview/MissionStatusDisplay.tsx
We were using failed icon for partially successful missions.
> Use warning icon for partially successful mission

- backend/api/EventHandlers/MissionScheduler.cs
- frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx
- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/components/Pages/MissionPage/StatusReason.tsx
Closes #401 
Shows status reasons in frontend.
We still need to send status reasons through MQTT to cover other cases than failing to start.
Example of status showing in mission page:
> Improvement - Show status reasons

- backend/api/Controllers/MissionController.cs
- backend/api/Controllers/Models/MissionQueryStringParameters.cs
- backend/api/Controllers/Models/QueryStringParameters.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Services/MissionService.cs
- backend/api/api.csproj
- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx
- frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx
- frontend/src/models/MissionQueryParameters.ts
This is important for pagination to make sense, you can't order on the client side if the response is paginated 
You can order the 10 items to be ordered by end time for example, but that page might still not hold the most recent end times
You need to be able to order on server side for this, and that's what this pull request does
> Feature ordering missions api

- .github/release.yml
Useful to know when creating releases that we need to apply migrations to databases in staging and prod if we promote from dev.
> Add DB changes to release notes

- backend/api.test/Mocks/IsarServiceMock.cs
- backend/api/Controllers/RobotController.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/Models/IsarStep.cs
- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Pages/RobotPage/LocalizationSection.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
- frontend/src/models/AssetDeck.ts
Dependent on https://github.com/equinor/isar/pull/456
Further improvement recommendations that aren't implemented here:
* Ignore localization tasks in MQTT to prevent warning
* Fetch only assetDecks for current asset in localization page
* Add asset to the localization mission (and decide if the localization missions should be handled/hidden when they show up in ongoing and mission history)
* Get feedback about success/failure of localization to user
* Present localization pose in map
* Only make localization available for robots that support localization 
* Disable localization button if robot is busy
> Localization mission

- frontend/src/api/ApiCaller.tsx
- frontend/src/api/AuthConfig.tsx
- frontend/src/components/Contexts/APIUpdater.tsx
- frontend/src/components/Contexts/AuthProvider.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Pages/FlotillaSite.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/FailedMissionAlertView.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlButtons.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusView.tsx
- frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx
- frontend/src/components/Pages/MissionPage/MapPosition/MapView.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
- frontend/src/components/Pages/RobotPage/LocalizationSection.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/utils/timeout.tsx
Closes #678 
Refresh tokens are handled by the MSAL framework
Our problem was that these were not propagated to the API caller as this was only instantiated at the start of a render.
Now, the API caller is static and being updated using contexts for asset code and access token
> Fix token updates in api caller

- README.md
Add links to aurora deployments and badges for the deployment pipelines.
Note: The badges might currently be bugged (https://github.com/actions/starter-workflows/issues/1525)
> Update README with deployments in Aurora

- .github/workflows/deploy_to_development.yml
- .github/workflows/deploy_to_staging.yml
- .github/workflows/promote_to_production.yml
This is needed to properly trigger the deployments in github.
We use these to protect our deployments (they need to be approved)
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#required-reviewers
> Add deployment triggers to deployment workflows

- backend/api/Database/Models/Mission.cs
- backend/api/Migrations/20230508063416_ChangeEstimatedDurationToInt.Designer.cs
- backend/api/Migrations/20230508063416_ChangeEstimatedDurationToInt.cs
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueCard.tsx
- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/models/Mission.ts
The old type "TimeSpan" is not widely supported.
Int is simpler and leaves less room for misinterpretation, no need for string parsing on the client side of our API.
> Use int for estimated duration

- backend/README.md
This is needed for local development on linux, and was causing the issue where you sometimes had to go to the local backend and click "proceed" in order for the frontend to work.
This was due to the browser not trusting the certificate from the backend, causing the https to be declined, trigger in a Cross-Origin Resource Sharing (CORS) error.
> Add HTTPS dev certificate instructions to readme

- backend/api/Program.cs
Closes #437 
Typing localhost:8000 into the browser now redirects to https://localhost:8000/swagger/index.html
> Adding redirect to swagger from base URL

- frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlButtons.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx
Closes #827 
If anyone has an idea of how to remove the border on the mission title card, that would be great but I don't think the [eds-storybook-react](https://eds-storybook-react.azurewebsites.net/?path=/docs/surfaces-card--introduction) allows it. It could be changed into a button but I prefer how it looks with the card since it's bigger.
> Add hover icons on ongoing mission card

- backend/api/Database/Models/MissionMap.cs
If the coordinates were selected in the wrong order for a map the system would not work.
Also, if they were in the wrong order tha transformation would not be ideal. Thus, X1 should always be the smaller value compared to X2 etc.
> Set boundaries to min and max values automatically

- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Models/MissionDefinition.cs
- backend/api/Migrations/20230830075517_RemoveInspectionFrequency.Designer.cs
- backend/api/Migrations/20230830075517_RemoveInspectionFrequency.cs
- backend/api/Migrations/20230830075801_FormatTimeSpanAsBigInt.Designer.cs
- backend/api/Migrations/20230830075801_FormatTimeSpanAsBigInt.cs
> Fix inspection frequency backend crash

- backend/api/appsettings.Development.json
- backend/api/appsettings.Production.json
- backend/api/appsettings.Staging.json
- backend/api/appsettings.json
As of .NET 7.0 we are required to configure the scopes as an array of strings otherwise an unauthenticated call will be attempted.
See https://github.com/AzureAD/microsoft-identity-web/blob/master/docs/blog-posts/downstreamwebapi-to-downstreamapi.md for reference.
> Use array of scopes for downstream API config

- backend/api.test/Mocks/BlobServiceMock.cs
- backend/api.test/Mocks/CustomMissionServiceMock.cs
- backend/api/Controllers/MissionController.cs
- backend/api/Services/BlobService.cs
- backend/api/Services/CustomMissionService.cs
- backend/api/Utilities/Exceptions.cs
Closes #968 
Worth noting that in order to catch exceptions when uploading the blobs, the blob uploading needs to be awaited.
The container name fix is done in the robotics infrastructure, here we just handle the potential exception.
> Handle exceptions when uploading blob

- backend/api/Controllers/Models/EchoInspection.cs
- backend/api/Services/EchoService.cs
- frontend/src/language/en.json
- frontend/src/language/no.json
> Filter sensor types by distinct values

- frontend/README.md
A list with supported/tested web browsers is usefull, but it is  removed for now as it is not maintained.
> Remove list of web browsers in README

- backend/api/EventHandlers/IsarConnectionEventHandler.cs
Was not able to identify the issue but made a small refactor to improve readability
> Refactor add timer functionality

- backend/api.test/Mocks/RobotControllerMock.cs
- backend/api/Controllers/RobotController.cs
- backend/api/Database/Models/Pose.cs
- backend/api/EventHandlers/IsarConnectionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/MQTT/MessageModels/IsarPoseMqtt.cs
- backend/api/Program.cs
- backend/api/Services/ActionServices/PoseTimeseriesService.cs
- backend/api/Services/MissionDefinitionService.cs
- backend/api/Services/RobotService.cs
> Fix concurrency issues for updating robot object

- frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx
> Create consistent ordering of inspections

- frontend/src/components/Pages/FrontPage/FrontPage.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionView.tsx
Solves #1108 
I'll suggest to place the stop button above the mission overview as shown on the attached screenshots, but open for other opinions. A suggestion in the future is also to fix the stop button such that it is always available in the same position on the screen, as suggested in #901.
> Move stop all robots button

- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MissionScheduling.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Program.cs
- backend/api/Services/MissionSchedulingService.cs
The additional scoped service which was used to handle the RobotAvailable event caused events to sometimes be handled by two different objects at the same time.
> Remove duplicate scoped event handler

- backend/api/Controllers/MissionDefinitionController.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Models/Inspection.cs
- backend/api/Database/Models/MissionTask.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Migrations/20231109194856_MakeInspectionNotOwned.Designer.cs
- backend/api/Migrations/20231109194856_MakeInspectionNotOwned.cs
- backend/api/Migrations/20231109195524_MakeMissionTaskNotOwned.Designer.cs
- backend/api/Migrations/20231109195524_MakeMissionTaskNotOwned.cs
- backend/api/Program.cs
- backend/api/Services/InspectionService.cs
- backend/api/Services/MissionDefinitionService.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionTaskService.cs
- backend/api/Utilities/Exceptions.cs
- frontend/src/components/Contexts/SignalRContext.tsx
As these were owned by `MissionRun` the only method of updating the status of each of them was to update the entire `MissionRun`. As this happens in three parallel event handlers these were overwriting eachother. 
Closes #1141
> Make `Inspection` and `MissionTask` not owned entities

- backend/api/Controllers/RobotController.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/MissionSchedulingService.cs
If the robot is reported as idle from ISAR, stopping a mission should not crash
> Stop mission if robot is idle

- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
> Keep the header sticky on the mission page

- backend/api.test/Client/MissionTests.cs
- backend/api/Controllers/MissionRunController.cs
- backend/api/Controllers/Models/AreaResponse.cs
- backend/api/Controllers/Models/MissionRunResponse.cs
- backend/api/Controllers/Models/RobotResponse.cs
- backend/api/Services/MissionRunService.cs
- frontend/src/components/Pages/MissionHistoryPage/HistoricMissionCard.tsx
- frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx
- frontend/src/models/Mission.ts
MissionRunResponse.cs was made in addition to adjustments to missionRunController.cs and missionRunService.cs. 
Related to this, an area column was added to the Mission History Page (as suggested in #1060).
> Add missionRunResponse model to backend

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Displays/RobotDisplays/BatteryStatusDisplay.tsx
- frontend/src/components/Displays/RobotDisplays/PressureStatusDisplay.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
> Refactor pressure and battery display

- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/EventHandlers/InspectionFindingsEventHandler.cs
- backend/api/Migrations/20231124081038_InspectionFindingReport.Designer.cs
- backend/api/Migrations/20231124081038_InspectionFindingReport.cs
- backend/api/Program.cs
- backend/api/Services/InspectionFindingsService.cs
- backend/api/Services/InspectionService.cs
- backend/api/appsettings.json
This pull request implements the service responsible for cronjob functionality described here #1102
> Make a cronjob functionality intended for InspectionReportGeneration

- frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/NoMissionsDialog.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
> Improve appearance of no missions available dialog

- backend/api/Services/MissionRunService.cs
> Remove LINQ errors for filtering

- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Contexts/MissionControlContext.tsx
- frontend/src/components/Contexts/MissionListsContext.tsx
- frontend/src/components/Displays/MissionButtons/MissionControlButtons.tsx
- frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
- frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx
- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
- frontend/src/components/Pages/MissionPage/StatusReason.tsx
- frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/utils/EnumTranslations.tsx
- frontend/src/utils/MapMarkers.tsx
> Remove polling and refactor mission page

- backend/api.test/Client/RoleAccessTests.cs
- backend/api.test/DbContextTestSetup.cs
- backend/api.test/Mocks/HttpContextAccessorMock.cs
- backend/api.test/TestWebApplicationFactory.cs
- backend/api/Controllers/AccessRoleController.cs
- backend/api/Controllers/Models/CreateAccessRoleQuery.cs
- backend/api/Services/AccessRoleService.cs
Closes #1212 
It uses adding and access plants as an example for granular access.
> Utilise non-admin roles in tests

- backend/api/Controllers/Models/AlertResponse.cs
- backend/api/Database/Context/InitDb.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- frontend/src/App.tsx
- frontend/src/components/Alerts/FailedSafeZoneAlertContent.tsx
- frontend/src/components/Contexts/AlertContext.tsx
- frontend/src/components/Contexts/SignalRContext.tsx
- frontend/src/components/Pages/FlotillaSite.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusSection.tsx
- frontend/src/models/Alert.ts
> Add alert for failure to send robot to safe zone

- frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/ScheduleMissionDialog.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
Translation for `Failed to schedule mission ${mission.name}` is still missing
> Add translation for failed request alerts

- frontend/src/components/Alerts/BlockedRobotAlert.tsx
- frontend/src/components/Contexts/AlertContext.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusSection.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
* Moved to alertContext such that the banner will be updated regardless of viewed paged
* Removed setAlert from dependency in useEffect to fix warning (see linked issue)
* Only call setAlert when blockedRobotNames are changed such that the banner can be dismissed. Will reappear if changes to which robots are blocked or if page is refreshed
* Updated banner to display alternative text if more than on robot is blocked
> Improve blocked alert

- frontend/src/components/Header/Header.tsx
- frontend/src/components/Pages/FrontPage/FrontPage.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueCard.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
- frontend/src/components/Pages/InspectionPage/InspectionTable.tsx
- frontend/src/components/Pages/InspectionPage/InspectionUtilities.tsx
- frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
- frontend/src/components/Styles/StyledComponents.tsx
> Refactor front page for iphone use

- backend/api/Controllers/Models/RobotResponse.cs
- backend/api/Database/Models/Area.cs
- backend/api/Database/Models/Deck.cs
- backend/api/Database/Models/DefaultLocalizationPose.cs
- backend/api/Database/Models/Inspection.cs
- backend/api/Database/Models/InspectionFinding.cs
- backend/api/Database/Models/MissionRun.cs
- backend/api/Database/Models/MissionTask.cs
- backend/api/Database/Models/Plant.cs
- backend/api/Database/Models/Pose.cs
- backend/api/Database/Models/Robot.cs
- backend/api/Database/Models/SortableRecord.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/Migrations/20240104142156_MakeDeckInAreaRequired.Designer.cs
- backend/api/Migrations/20240104142156_MakeDeckInAreaRequired.cs
- backend/api/Migrations/20240104143242_MakeCurrentRobotInstallationRequired.Designer.cs
- backend/api/Migrations/20240104143242_MakeCurrentRobotInstallationRequired.cs
- backend/api/Migrations/20240112094731_AddRequiredFieldsToInspectionAndPoses.Designer.cs
- backend/api/Migrations/20240112094731_AddRequiredFieldsToInspectionAndPoses.cs
- backend/api/Services/LocalizationService.cs
- backend/api/Services/Models/IsarMissionDefinition.cs
- backend/api/Services/ReturnToHomeService.cs
> Make more fields required

- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
> Refactor ongoing mission page for iphone use

- backend/api/Services/ActionServices/PressureTimeseriesService.cs
- frontend/src/components/Displays/RobotDisplays/PressureStatusDisplay.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
This is a fix for:
* If pressure is null it will never get updated and will stay null
* If upperPressureWarningThreshold or lowerPressureWarningThreshold is null, the pressure icon will show but the pressure value is missing
> Fix missing pressure on new robots

- backend/api/Database/Models/MissionTask.cs
- backend/api/Migrations/20240126115524_MakeInspectionTargetOptional.Designer.cs
- backend/api/Migrations/20240126115524_MakeInspectionTargetOptional.cs
- backend/api/Services/MapService.cs
- frontend/src/models/Task.ts
- frontend/src/utils/MapMarkers.tsx
* Task.InspectionTarget should be removed as it is replaced by Inspection.InspectionTarget, but first existing custom missions needs to be adapted to the change. It will temporary be set to optional to allow removal in custom missions.
* If a task has several inspections with different inspectionTargets, the current solution will display them all with the same task number in the mission map. Improvement for this can be solved as new issue.
> Remove use of Task.InspectionTarget

- setup.sh
A difference in Windows / Mac seems to interpret strings from environment variables differently. Removing quotation marks seems to work on both OS
> Removed quotation mark in environment files

- backend/api/Controllers/Models/MissionRunResponse.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Context/InitDb.cs
- backend/api/Database/Models/MissionRun.cs
- backend/api/Migrations/20240129130002_AddMissionRunCounter.Designer.cs
- backend/api/Migrations/20240129130002_AddMissionRunCounter.cs
- backend/api/Program.cs
- backend/api/Services/MissionRunService.cs
> Add missionRun counter

- backend/api.test/Database/DatabaseUtilities.cs
- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api.test/Mocks/SignalRServiceMock.cs
- backend/api.test/Mocks/TaskDurationServiceMock.cs
- backend/api.test/Services/MissionService.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/Events/MissionEventArgs.cs
- backend/api/Services/LocalizationService.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/Models/AlertResponse.cs
- backend/api/Services/ReturnToHomeService.cs
- backend/api/Services/SignalRService.cs
- backend/api/Utilities/Exceptions.cs
Main fix: Current area is set based on result from localization mission.
Other changes:
- Add new event OnMissionCompleted
- Needed in the case of localization mission. We need to know the status of this mission when it completes before we have enough information to decide which mission (if any) to run next.
- Refactoring
> Fix localization failure bug and refactor

- frontend/src/components/Alerts/AlertsBanner.tsx
- frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx
**First bug**
When scrolling, the shadow from the failed mission card was visible on the sides of the main header. This PR reduces the size of the failed mission card.
**Images to illustrate pre PR**
**Images to illustrate post PR**
> Frontend bug fixes, failed mission card and front page

- backend/api/Database/Models/MissionRun.cs
This undoes the fix for UTC time in the frontend. Although the DateTime "kind" is set to unspecified when fetching from the database, we cannot set values in the database to any kind other than "UTC". When we send a datetime with kind "UTC" to the frontend however, it is interpreted as local time, which causes a time offset.
Reopens https://github.com/equinor/flotilla/issues/1442
> Remove fix for UTC time. Not postgres compatible

- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api/Controllers/EmergencyActionController.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/RobotService.cs
> Improve send robots to safe zone during localization mission

- backend/api/Services/EchoService.cs
- frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
- frontend/src/utils/MapMarkers.tsx
Explanation for the bug:
When fetching missions from Echo, the first task is given the "PlanOrder"/"SortingOrder" 0 and all the rest get 2147483647. When sending this to ISAR we then currently ignore PlanOrder and just assume the order we get it from the backend is correct:
(screenshot from IsarMissionDefinition.cs, line 31)
PlanOrder/SortingOrder seems to only ever be used on the frontend to display the order. It might therefore be safe to ignore this value and just use the order of the items in the list of tasks, since that is what we do for ISAR anyways.
We could potentially also close issue #1453 if we just ignore "taskOrder" in the frontend and only use the index, but I would like some feedback on this first. UPDATE: we now ignore Echo taskOrder, so this PR will also close #1453 . …
> Prevent many tasks being indexed with index 1

- backend/api.test/Client/MissionTests.cs
- backend/api/Controllers/Models/CreateRobotQuery.cs
- backend/api/Controllers/Models/RobotResponse.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Models/Robot.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/MQTT/MessageModels/IsarRobotInfo.cs
- backend/api/Migrations/20240403071238_AddRobotCapabilitesToRobot.Designer.cs
- backend/api/Migrations/20240403071238_AddRobotCapabilitesToRobot.cs
See https://github.com/equinor/isar/pull/534 for context.
> Add ISAR robot capabilities info to robot

- backend/api/Controllers/MissionSchedulingController.cs
- backend/api/Database/Models/Inspection.cs
- backend/api/Services/LocalizationService.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/ReturnToHomeService.cs
- backend/api/Utilities/Exceptions.cs
Closes #1534 
Here is how it currently looks: 
If we want we can catch it in the frontend to make a more unique error for it.
> Return error when using unsupported sensors

- frontend/src/components/Pages/MissionHistoryPage/HistoricMissionCard.tsx
- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/utils/StringFormatting.tsx
Time varies between having a z at the and not having it. If there is a z, typescript will assume that the time is given as UTCtime and if not it will assume that its local time
Console log of time values and corresponding new Date(). Note the marked time and the corresponding time on the line above
Best would be to fix such that backend always sends the same but this is an alternative solution
> Fix mix between UTC and local time

- backend/api/Controllers/MissionSchedulingController.cs
Partly addresses #1567. Issues still remain if most tags are on a different deck, as this deck will be used as the "main" deck.
> Allow tags in several decks in missions

- backend/api/Database/Models/MissionRun.cs
- backend/api/EventHandlers/IsarConnectionEventHandler.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/ActionServices/BatteryTimeseriesService.cs
- backend/api/Services/ActionServices/PoseTimeseriesService.cs
- backend/api/Services/ActionServices/PressureTimeseriesService.cs
If we have an unhandled exception in an event handler, then Flotilla crashes. This will prevent this in most cases. I have not added try/catch for all the database "Update" calls, even though these can return database exceptions, since we need a more systematic solution for these.
> Add exception handling in event handlers

- backend/api/Services/RobotService.cs
Will close one of the points in [#1592](https://github.com/equinor/flotilla/issues/1592).
Prior to this PR:
* When robot was offline the user could schedule missions but missions would not appear in mission queue.
* When robot had connection issues (isarConnected=false), the user could schedule missions, the missions would appear in queue, but the missions would not run even if isar connection was re-established.
After this PR:
* The user will not be able to schedule mission if the robot is offline or has connection issues. They will get an error banner with an explanation to the problem.
> Add offline and isarConnected prechecks

- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
If localization mission update happens at the
same time as isar status update. It sometimes
happens that the updates from OnIsarMissionUpdate
overwrites the robot status.
> Give localization mission time to complete

- backend/api.test/Database/DatabaseUtilities.cs
- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api/Database/Models/MissionTask.cs
- backend/api/EventHandlers/MqttEventHandler.cs
> Use first mission task status to localize robot

- frontend/src/App.tsx
- frontend/src/components/Contexts/AlertContext.tsx
- frontend/src/components/Contexts/InstallationContext.tsx
- frontend/src/components/Contexts/MissionControlContext.tsx
- frontend/src/components/Contexts/MissionDefinitionsContext.tsx
- frontend/src/components/Contexts/MissionRunsContext.tsx
- frontend/src/components/Contexts/RobotContext.tsx
- frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
- frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx
- frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
It is worth noting that error messages that use the FailedRequestAlertContent component, do not update their translations when the selected language changes. I am looking into this, but it is not a large priority since this is a very niche issue,
> Add missing error handling in frontend

- frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx
- frontend/src/components/Pages/InspectionPage/InspectionSection.tsx
I noticed that we were only checking that deck names were matching, but not that the inspections belonged to the right installation. This solves that issue. 
A more permanent solution might be to limit all the mission runs available in the MissionRunsContext to only those of the relevant installation, but this makes it potentially more complicated to switch installations.
> Verify installation for inspections in the inspection table

- backend/api/appsettings.json
> Add detailed signalR logs

- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Utilities/Exceptions.cs
This database exception would previously crash the backend. We likely want to add the same exception check elsewhere.
> Handle database error in event handler

- backend/api.test/Database/DatabaseUtilities.cs
- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api/Services/MissionSchedulingService.cs
> Only schedule return home if supported by robot

- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api/Controllers/EmergencyActionController.cs
- backend/api/Controllers/Models/RobotResponse.cs
- backend/api/Database/Models/MissionRun.cs
- backend/api/Database/Models/Robot.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Migrations/20240724102244_AddRobotFlotillaStatus.Designer.cs
- backend/api/Migrations/20240724102244_AddRobotFlotillaStatus.cs
- backend/api/Services/ActionServices/BatteryTimeseriesService.cs
- backend/api/Services/ActionServices/PressureTimeseriesService.cs
- backend/api/Services/EmergencyActionService.cs
- backend/api/Services/Events/MissionEventArgs.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/RobotService.cs
- frontend/src/components/Contexts/SafeZoneContext.tsx
- frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
- frontend/src/models/Robot.ts
> Make robot go home when battery or pressure levels are outside safe limits

- frontend/src/components/Displays/RobotDisplays/BatteryStatusDisplay.tsx
- frontend/src/components/Displays/RobotDisplays/PressureStatusDisplay.tsx
- frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx
- frontend/src/components/Pages/FrontPage/RobotCards/RobotStatusCard.tsx
- frontend/src/language/no.json
> Fix overflow and line break style on robot button cards

- backend/api/Controllers/MissionSchedulingController.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/RobotService.cs
There was an issue where rerunning missions didn't work since an entity framework robot instance got tracked twice in the same thread. This seems to fix that. We now don't track objects we aren't planning on updating within the rerun function. We will want to do this in more places in the future.
> Avoid double-tracking robot entry

- backend/api/Controllers/AccessRoleController.cs
- backend/api/Controllers/AreaController.cs
- backend/api/Controllers/DeckController.cs
- backend/api/Controllers/InstallationController.cs
- backend/api/Controllers/MissionDefinitionController.cs
- backend/api/Controllers/MissionRunController.cs
- backend/api/Controllers/MissionSchedulingController.cs
- backend/api/Controllers/PlantController.cs
- backend/api/Controllers/RobotController.cs
- backend/api/Controllers/RobotModelController.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/AccessRoleService.cs
- backend/api/Services/ActionServices/TaskDurationService.cs
- backend/api/Services/AreaService.cs
- backend/api/Services/DeckService.cs
- backend/api/Services/InstallationService.cs
- backend/api/Services/LocalizationService.cs
- backend/api/Services/MissionDefinitionService.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/PlantService.cs
- backend/api/Services/ReturnToHomeService.cs
- backend/api/Services/RobotModelService.cs
- backend/api/Services/RobotService.cs
- backend/api/Services/StidService.cs
By using readOnly capabilities more often we are able to be more precise with our database operations, preventing future bugs. This will also speed up the code somewhat as there are fewer checks performed when not tracking objects within an entity framework context.
We currently also manually set many object to have the entity state "detached" in the code to prevent them from being updated. I believe that by refraining from tracking these objects we may sometimes be able to avoid this "hacky" behaviour, but I am cautious about doing this in this PR. We should try to make a PR though where we investigate everywhere we use this entry state statement, and instead try to not track the object.
> Use entity framework read only in more places

- backend/api.test/Database/DatabaseUtilities.cs
- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api.test/Services/MissionService.cs
- backend/api.test/Services/RobotService.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Models/UserInfo.cs
- backend/api/Migrations/20240813114738_AddUserInfoTable.Designer.cs
- backend/api/Migrations/20240813114738_AddUserInfoTable.cs
- backend/api/Program.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/UserInfoServices.cs
- backend/api/Utilities/HttpContextExtensions.cs
Issue #1569, also linked to #1088
> Logging who runs a robot mission (action log in flotilla)

- frontend/src/components/Alerts/AlertsBanner.tsx
- frontend/src/components/Alerts/AlertsListItem.tsx
- frontend/src/components/Alerts/BlockedRobotAlert.tsx
- frontend/src/components/Alerts/FailedAlertContent.tsx
- frontend/src/components/Alerts/FailedMissionAlert.tsx
- frontend/src/components/Alerts/FailedRequestAlert.tsx
- frontend/src/components/Alerts/SafeZoneAlert.tsx
- frontend/src/components/Contexts/AlertContext.tsx
- frontend/src/components/Contexts/InstallationContext.tsx
- frontend/src/components/Contexts/MissionControlContext.tsx
- frontend/src/components/Contexts/MissionDefinitionsContext.tsx
- frontend/src/components/Contexts/MissionRunsContext.tsx
- frontend/src/components/Contexts/RobotContext.tsx
- frontend/src/components/Contexts/SafeZoneContext.tsx
- frontend/src/components/Displays/MissionButtons/MissionRestartButton.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Pages/AssetSelectionPage/AssetSelectionPage.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/ScheduleMissionDialog/SelectMissionsToScheduleDialog.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
- frontend/src/components/Pages/InspectionPage/InspectionOverview.tsx
- frontend/src/components/Pages/InspectionPage/ScheduleMissionDialogs.tsx
- frontend/src/components/Pages/MissionDefinitionPage/MissionDefinitionPage.tsx
- frontend/src/components/Pages/MissionHistoryPage/MissionHistoryView.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
First PR for #1560. Further design and functionalities should be discussed in UX meeting
> Implement alert list feature

- backend/api/Services/MissionRunService.cs
- backend/api/Services/UserInfoServices.cs
The removed exception and its logWarning currently runs whenever a mission is created in an event handler, so it was bloating the log somewhat.
> Limit logging when fetching user info

- docker-compose.yml
- frontend/Dockerfile
- frontend/src/config.ts
Replaces frontend environment variable non-null assertion with a check for existence.
Resolves #1215.
> Check for undefined environment variables

- backend/api/Controllers/Models/UpdateRobotModelQuery.cs
- backend/api/Database/Models/Robot.cs
- backend/api/Database/Models/RobotModel.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Migrations/20241015070506_AddRobotMissionStartBatteryThreshold.Designer.cs
- backend/api/Migrations/20241015070506_AddRobotMissionStartBatteryThreshold.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/MissionSchedulingService.cs
This PR removes a lot of failure points and instabilities in the safezone (and therefore also the charging) functionality. In a future PR I also want to implement this: https://github.com/equinor/flotilla/issues/1775 to further improve consistency. In this PR we now use localization poses if no safezone poses are found. In a future PR I would also like to handle this issue: https://github.com/equinor/flotilla/issues/1528 by removing safezone poses and only using localization poses.
> Improve safezone stability

- backend/api/Database/Context/InitDb.cs
- frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx
> Show robot as busy when driving home

- frontend/src/components/Displays/MissionButtons/MissionControlButtons.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/StopDialogs.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
> Implement robot specific stop button

- backend/api/Controllers/InspectionController.cs
- backend/api/Controllers/Models/CustomMissionQuery.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Models/MissionTask.cs
- backend/api/Database/Models/TagInspectionMetadata.cs
- backend/api/Migrations/20241210115843_AddInspectionTagMetadataTable.Designer.cs
- backend/api/Migrations/20241210115843_AddInspectionTagMetadataTable.cs
- backend/api/Services/EchoService.cs
- backend/api/Services/Models/IsarMissionDefinition.cs
This adds an endpoint where we can map an echo tag ID to a zoom value. This is not meant as a permanent solution, but it can be used until an Echo solution is created.
> Let user configure custom zoom for tasks

- backend/api.test/Mocks/MissionLoaderMock.cs
- backend/api/Database/Context/InitDb.cs
- backend/api/Database/Models/Inspection.cs
- backend/api/Database/Models/MissionTask.cs
- backend/api/Migrations/20241210132255_AddDescriptionToInspections.Designer.cs
- backend/api/Migrations/20241210132255_AddDescriptionToInspections.cs
- backend/api/Services/EchoService.cs
- backend/api/Services/MissionLoaders/EchoInspection.cs
- frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
> Use echo inspection target name as tag description

- backend/api/EventHandlers/MqttEventHandler.cs
> Do not report failed telemetry to frontend

- backend/api/Controllers/InspectionController.cs
- backend/api/Program.cs
- backend/api/Services/InspectionService.cs
- backend/api/Services/Models/IDAInspectionDataResponse.cs
- backend/api/appsettings.Development.json
- backend/api/appsettings.Local.json
- backend/api/appsettings.Production.json
- backend/api/appsettings.Staging.json
- backend/api/appsettings.json
- frontend/src/App.tsx
- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Contexts/InpectionsContext.tsx
- frontend/src/components/Pages/InspectionReportPage.tsx/InspectionStyles.tsx
- frontend/src/components/Pages/InspectionReportPage.tsx/InspectionView.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
- frontend/src/components/Pages/MissionPage/TaskOverview/TaskTable.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
> New inspections view

- backend/api/Controllers/Models/RobotResponse.cs
- backend/api/Database/Models/Robot.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/MQTT/MessageModels/IsarBattery.cs
- backend/api/Migrations/20241217085716_AddBatteryStateToRobot.Designer.cs
- backend/api/Migrations/20241217085716_AddBatteryStateToRobot.cs
- backend/api/Services/RobotService.cs
- frontend/src/components/Displays/RobotDisplays/BatteryStatusDisplay.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/RobotCard.tsx
- frontend/src/components/Pages/RobotPage/RobotPage.tsx
- frontend/src/models/Robot.ts
Related to: https://github.com/equinor/isar/pull/675
> Use robotState to see if robot is charging

- backend/api/Controllers/Models/UpdateRobotQuery.cs
- backend/api/Controllers/RobotController.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/ActionServices/BatteryTimeseriesService.cs
- backend/api/Services/ActionServices/PressureTimeseriesService.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/RobotService.cs
- backend/api/Utilities/Exceptions.cs
> Improve mission starting stability

- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/Services/Events/MissionEventArgs.cs
> Remove unneeded nullability in event args

- .github/workflows/frontend_lint_and_test.yml
> Use npm instead of yarn in workflows

- frontend/src/components/Pages/InspectionReportPage.tsx/InspectionView.tsx
> Make inspection report dialog dismissable

- backend/api/Controllers/InspectionController.cs
- backend/api/Services/InspectionService.cs
- frontend/package-lock.json
- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Pages/InspectionReportPage.tsx/InspectionView.tsx
- frontend/src/models/Inspection.ts
by moving more functionality to the inspection service and avoiding a call to the Flotilla database
by using the ISAR Inspection ID directly from the frontend to make the call to the IDA API
> Simplify inspection controller

- backend/api/Services/MissionDefinitionService.cs
- frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx
- frontend/src/models/Mission.ts
- frontend/src/models/MissionDefinition.ts
> Fix fetching map on mission page

- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api.test/Services/RobotService.cs
- backend/api/Controllers/EmergencyActionController.cs
- backend/api/Controllers/RobotController.cs
- backend/api/EventHandlers/IsarConnectionEventHandler.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/Events/MissionEventArgs.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/RobotService.cs
> Make event handlers more deterministic

- frontend/src/components/Pages/MissionPage/MapPosition/MissionMapView.tsx
- frontend/src/components/Pages/MissionPage/MissionPage.tsx
> Improve mission map appearance

- backend/api/Database/Models/Robot.cs
- frontend/src/components/Displays/RobotDisplays/RobotStatusIcon.tsx
- frontend/src/models/Robot.ts
> Add blocked protective stop

- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueView.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
> Add header to mission queue

- backend/api.test/EventHandlers/TestMissionEventHandler.cs
- backend/api.test/Services/MissionRunService.cs
- backend/api.test/Services/MissionSchedulingService.cs
- backend/api/Controllers/ReturnToHomeController.cs
- backend/api/Controllers/RobotController.cs
- backend/api/EventHandlers/IsarConnectionEventHandler.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/ReturnToHomeService.cs
> Move create return home to starting mission

- frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx
- frontend/src/utils/IsRobotReadyToRunMissions.tsx
> Fix order of hooks error

- backend/api.test/Services/RobotService.cs
- backend/api/Controllers/InspectionAreaController.cs
- backend/api/Controllers/MissionDefinitionController.cs
- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/AccessRoleService.cs
- backend/api/Services/AreaService.cs
- backend/api/Services/DefaultLocalizationPoseService.cs
- backend/api/Services/InspectionAreaService.cs
- backend/api/Services/InspectionService.cs
- backend/api/Services/InstallationService.cs
- backend/api/Services/MissionDefinitionService.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/MissionTaskService.cs
- backend/api/Services/PlantService.cs
- backend/api/Services/RobotModelService.cs
- backend/api/Services/RobotService.cs
- backend/api/Services/SourceService.cs
- backend/api/Services/UserInfoServices.cs
> Fix various tracking issues

- backend/api/Services/StidService.cs
> Use different API call type for STID

- backend/api.test/Mocks/IsarServiceMock.cs
- backend/api/Controllers/MediaStreamController.cs
- backend/api/Services/IsarService.cs
- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Contexts/MediaStreamContext.tsx
Dependent on https://github.com/equinor/isar/pull/698
> Handle empty media stream config

- backend/api/api.csproj
> Update System.Linq.Dynamic.Core to 1.6.0

- backend/api/Controllers/ReturnToHomeController.cs
- backend/api/Services/MissionRunService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/ReturnToHomeService.cs
> Inspect return to home

- frontend/src/components/Pages/InspectionReportPage/InspectionView.tsx
> Allow switching of inspection by using key arrows

- .github/workflows/runMigrations.yml
- backend/api/Controllers/MissionSchedulingController.cs
- backend/api/Controllers/Models/MissionRunResponse.cs
- backend/api/Database/Models/MissionRun.cs
- backend/api/Migrations/20250130081334_RenameEstimatedDuration.Designer.cs
- backend/api/Migrations/20250130081334_RenameEstimatedDuration.cs
- backend/api/Services/Models/IsarMissionDefinition.cs
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionQueueCard.tsx
- frontend/src/components/Pages/MissionPage/MissionHeader/MissionHeader.tsx
- frontend/src/models/Mission.ts
- frontend/src/utils/CalculateRemaingingTime.tsx
> Improve estimate for remainding time

- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/MQTT/MessageModels/IdaInspectionResult.cs
- backend/api/MQTT/MqttService.cs
- backend/api/MQTT/MqttTopics.cs
- backend/api/appsettings.Development.json
- backend/api/appsettings.Local.json
- backend/api/appsettings.Production.json
- backend/api/appsettings.Staging.json
- backend/api/appsettings.Test.json
- broker/mosquitto/config/access_control
- frontend/src/App.tsx
- frontend/src/components/Contexts/InpectionsContext.tsx
- frontend/src/components/Contexts/SignalRContext.tsx
- frontend/src/components/Pages/InspectionReportPage/InspectionReportUtilities.tsx
- frontend/src/components/Pages/InspectionReportPage/InspectionStyles.tsx
- frontend/src/components/Pages/InspectionReportPage/InspectionView.tsx
- frontend/src/models/Inspection.ts
> Use IDA MQTT message to update inspection view

- backend/api/Services/RobotService.cs
> Change pressure log to debug level

- backend/api/Controllers/InspectionAreaController.cs
- backend/api/Controllers/Models/CreateDefaultLocalizationPose.cs
- backend/api/Database/Models/DefaultLocalizationPose.cs
- backend/api/Database/Models/Robot.cs
- backend/api/Migrations/20250205142937_RemoveDockingEnabled.Designer.cs
- backend/api/Migrations/20250205142937_RemoveDockingEnabled.cs
- backend/api/Services/InspectionAreaService.cs
- backend/api/Services/Models/IsarMissionDefinition.cs
- frontend/src/models/Robot.ts
Related to https://github.com/equinor/isar/pull/708
> Remove dock/undock from isar missions

- frontend/src/components/Pages/InspectionReportPage/InspectionStyles.tsx
- frontend/src/components/Pages/InspectionReportPage/InspectionView.tsx
> Fix inspection report for mobile

- backend/README.md
- backend/api.test/Database/DatabaseUtilities.cs
- backend/api/Database/Models/Robot.cs
- backend/api/Services/IsarService.cs
- backend/api/Services/Models/IsarMissionDefinition.cs
- frontend/src/models/Robot.ts
Will break if a isar-"robot" package has "localize" in capability list. Depends on this: https://github.com/equinor/isar-robot/pull/200
> Remove start pose from isar missions

- frontend/src/components/Contexts/InstallationContext.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Pages/FrontPage/FrontPage.tsx
- frontend/src/components/Pages/MissionHistoryPage/MissionHistoryPage.tsx
- frontend/src/utils/RedirectIfNoInstallationSelected.tsx
> Redirect to asset page if no installation selected

- backend/api/Controllers/Models/MissionDefinitionResponse.cs
- backend/api/Database/Context/FlotillaDbContext.cs
- backend/api/Database/Models/AutoScheduleFrequency.cs
- backend/api/Services/MissionDefinitionService.cs
> Fix delete feature of auto scheduling

- backend/api/Services/MissionSchedulingService.cs
> Do not check if return home mission is inside inspection area

- backend/api/EventHandlers/MissionEventHandler.cs
- backend/api/Services/MissionSchedulingService.cs
> Prevent backend from crashing if no inspectionArea

- frontend/src/components/Pages/FrontPage/AutoScheduleSection/AutoScheduleSection.tsx
- frontend/src/components/Pages/FrontPage/FrontPage.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
> Visualize auto scheduled missions

- backend/api/Database/Models/AutoScheduleFrequency.cs
> Consider timezones when autoScheduling

- backend/api/Controllers/MissionDefinitionController.cs
- backend/api/Services/MissionDefinitionService.cs
Closes #2115 - Solved by using update function
Closes #2061 - Solved by using MissionDefinitionResponse instead of MissionDefinitionWithTasksResponse
> Fix update error in delete mission def endpoint

- backend/api.test/Database/DatabaseUtilities.cs
- backend/api.test/Services/MissionSchedulingService.cs
- backend/api/Services/MissionSchedulingService.cs
- backend/api/Services/Models/InspectionAreaPolygon.cs
> Only cancel current mission outside inspection area

- frontend/src/components/Displays/MissionButtons/MissionControlButtons.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/MissionControlSection.tsx
- frontend/src/components/Pages/FrontPage/MissionOverview/OngoingMissionCard.tsx
- frontend/src/language/en.json
Looks like:
En:
No:
Pause button is removed for the placeholder since isar doesn't support pausing of return home missions
> Add mission placeholder for ongoing returnToHome

- backend/api/Controllers/Models/MissionRunQueryStringParameters.cs
- backend/api/Services/MissionRunService.cs
- frontend/src/api/ApiCaller.tsx
- frontend/src/components/Contexts/MissionFilterContext.tsx
- frontend/src/components/Pages/MissionHistory/FilterSection.tsx
- frontend/src/language/en.json
- frontend/src/language/no.json
- frontend/src/models/MissionRunQueryParameters.ts
Return to home functionality has been rewritten to be a state and not a missionRun. This filter will no longer be triggered.
> Remove unused excludeReturnToHome mission filter

- backend/api/Services/IsarService.cs
- backend/api/Services/Models/IsarMissionDefinition.cs
to contain inspection_description instead of metadata
This is needed to match change in ISAR: https://github.com/equinor/isar/pull/760
> Adjust IsarInspectionDefinition

- backend/api/Database/Models/Inspection.cs
- backend/api/Database/Models/Robot.cs
- backend/api/MQTT/MessageModels/IsarTask.cs
- backend/api/Services/EchoService.cs
- backend/api/Services/MissionLoaders/EchoInspection.cs
- backend/api/Services/Models/IsarTask.cs
The specification from Echo is specific to CO2 and has been added since the previous workaround of using the Audio type to perform a CO2 measurement. The workaround has now been removed and all relevant names changed to reflect CO2 measurements.
> Adjust support for CO2 measurement missions

- backend/api/Controllers/InspectionController.cs
- backend/api/Services/InspectionService.cs
- frontend/src/api/ApiCaller.tsx
Backend logging is replaced with throwing of errors. These errors get propagated to the frontend as part of the notFound message and visible in the console as shown below where the message is:
"Failed to GET /inspection/1fb646d7-efa6-4cd9-b1e2-4099af8bdffc: Could not find inspection image with ISAR Inspection ID1fb646d7-efa6-4cd9-b1e2-4099af8bdffc. Error of type 'System.Net.Http.HttpRequestException' with message 'Connection refused (localhost:8100)'."
> Remove backend logging for fetching of inspection results

- backend/api/EventHandlers/MqttEventHandler.cs
- backend/api/Services/MissionRunService.cs
- frontend/src/components/Contexts/AlertContext.tsx
To be reviewed after #2254, as there are dependencies
Currently, when a mission fails, its necessary to reload the page to get the "failed mission"-banner. This PR will fix that
> Update failed missions banner on new failed mission

- backend/api/Services/MissionRunService.cs
Currently if a mission fails to initiate or fail in any other way where flotilla doesn't receive a missionStatus update with status failed, the failed mission banner doesn't show up unless refreshing. Fixed in this PR
> Fix failed mission banner when failing to initiate

- backend/api/EventHandlers/MqttEventHandler.cs
- frontend/src/components/Alerts/FailedAlertContent.tsx
> Add SignalRMessage for return-home-failure
